UHH2/UHH2

- common/include/ElectronHists.h
- common/include/Utils.h
- common/src/ElectronHists.cxx
- common/src/Utils.cxx
No interface changes, all old code still works.
> closestParticle template function and histograms for ele efficiency and response

- common/include/JetHists.h
- common/src/JetHists.cxx
adding support for more jet collections through a handle
> changing common/JetHists

- common/include/JetHists.h
- common/src/JetHists.cxx
> larger eta bounds and csv discriminator

- common/src/ElectronHists.cxx
- common/src/MuonHists.cxx
> saner histogram bounds for response plots

- core/python/ntuplewriter.py
> Keep leptons from higgs decay

- common/src/JetHists.cxx
small changes: got rid of some .c_str(), changed the range of deltaRmin from 0-2 to 0-8 otherwise many events would not be drawn. tested that it compiles and worked, tested the add_iJet/TopJet function.
> changed range of deltaRmin Hists

- common/include/GenTools.h
- common/src/GenTools.cc
- core/include/Selection.h
I hope the documentation within the files is sufficient, otherwise let me know and I'll edit the pull request. Dom
> Modified AndSelection and implemented NGenParticleCalculator

- common/include/EventVariables.h
- common/include/ReconstructionHypothesisDiscriminators.h
- common/src/EventVariables.cxx
> HTlepCalculator only

- common/include/ElectronIds.h
- common/src/ElectronIds.cxx
New electron Ids added, including the Ids with noIso for electron channel analysis
> new electron ids

- common/include/TTbarReconstruction.h
- common/src/TTbarReconstruction.cxx
* added filling of "blep_v4" in standard ttbar reconstruction (HighMassTTbarReconstruction module)
* implemented ttbar reconstruction for events with a top-tagged jet (TopTagReconstruction module)
> updates for modules in TTbarReconstruction

- common/include/TauIds.h
- common/src/TauIds.cxx
added TauIDDecayModeFinding for a comparison with 8TeV. In addition, deltaR was changed for ak4.
> added decaymodefindingID

- common/include/JetCorrections.h
Dear Thomas, 
please check that this makes sense. Physically. =)
Best, -H
> adjust drmax to ak4 radius

- common/include/EventHists.h
- common/src/EventHists.cxx
adding a weights histogram with log bin bounds. Useful for debugging.
> Additional weights histogram with log bins from 1e-10 to 1e+10

- core/python/bsframe.py
- core/python/datablock.py
- core/python/xmlparser.py
I added the batch submission python framework we use here at FNAL on condor. It has been updated to UHH2.
Doug
> Added batch framework submission for FNAL

- core/include/Tau.h
- core/plugins/NtupleWriterLeptons.cxx
I added all missing variables given on the tau twiki page https://twiki.cern.ch/twiki/bin/view/CMS/TauIDRecommendation13TeV to Tau.h.
> new tau variables for run 2 added

- Makefile.common
- core/plugins/NtupleWriter.cc
- core/plugins/NtupleWriter.h
- core/python/ntuplewriter.py
https://github.com/UHH2/UHH2/commit/a94cbab1241c55b20df67c512641c48777235c19 solves https://github.com/UHH2/UHH2/issues/86. @dgonzal, the problem was still there, sorry for the confusion.
https://github.com/UHH2/UHH2/commit/f7c813496378f1e79808e9dd4ec83d812aae76f2 implements PFHT800 trigger emulation in Spring15 MC samples.
> Fixing missing pcm files and implementing PFHT800 emulation

- core/plugins/NtupleWriter.cc
for future reference, trigger object called by its name rather than using the number id
> improved code clarity for PFHT800 emulation

- core/python/ntuplewriter.py
Running on data is not yet working because some JetCorrectionsRecord is still missing.
> remove b-tagging from HTT; add first options for data

- core/python/bsframe.py
Fixed a problem in the NEvent check for Post Selection files
> BSFrame Fix

- common/include/CommonModules.h
- common/src/CommonModules.cxx
following issue  CommonModules #121
> added jetlepcleaner to CommonModules

- common/src/MCWeight.cxx
- common/test/PU-Reweighting.xml
- common/test/TestPUReweighting.cpp
> implemented PU re-weighting

- common/include/LuminosityHists.h
- common/src/LuminosityHists.cxx
> fixed bug in Lumi hists

- common/include/JetHists.h
- common/src/JetHists.cxx
gives the option to set a jet Id to the JetHists, and in this case only these jets are plotted.
> added Top/JetId to JetHists

- common/src/LuminosityHists.cxx
as far as I know this plot only makes sense for data ?
> only fill for data

- common/include/CommonModules.h
- common/include/JetIds.h
- common/src/CommonModules.cxx
- common/src/JetIds.cxx
- core/include/Jet.h
loose pf requierement added to CommonModules
> new Jet PF ID

- core/python/ntuplewriter.py
Running with 25ns does not work yet because the latest JEC files are still missing (required by the MET without HF calculation).
> switch for 25ns/50ns

- common/include/ElectronIds.h
- common/src/ElectronIds.cxx
* cherry-picked updates for common/ElectronIds (from #203) in the UHH2:master branch
> updates for common/ElectronIds [cherry-picked a7b15b9]

- core/python/bsframe.py
Hey,
I added some minor improvements to bsframe
Doug
> bsframe fixes

- common/include/JetCorrections.h
* cherry-picked a small fix from UHH2:master to UHH2:RunII_50ns
> missing declarations [cherry-picked 67f4b8e]

- core/src/AnalysisModuleRunner.cxx
Will this eventually be merged into master again?
> more info in context

- core/python/ntuplewriter.py
* update in core/python/ntuplewriter.py to correctly fill the triggering-MVA value for each electron in the ntuple
* https://twiki.cern.ch/twiki/bin/view/CMS/MultivariateElectronIdentificationRun2#Triggering_electron_MVA_details
> enabled electron triggering-MVA in ntuplewriter.py

- common/include/BTagCalibrationStandalone.h
- common/include/JetHists.h
- common/include/MCWeight.h
- common/src/BTagCalibrationStandalone.cc
- common/src/JetHists.cxx
- common/src/MCWeight.cxx
- scripts/create-btag-effiency-histos.py
- scripts/create-multi-dataset-xmlfiles.py
this pull request contains code for the application of btag-scale factors (through weights) and code for the measurement of the btag-efficiencies in MC. (Doxygen-style documentation is provided and a detailed explanation will follow in the next substructure-meeting)
This PR also applies to master and RunII_25ns_v2.
> BTag scale factors

- scripts/crab/CrabScript.py
- scripts/crab/multicrab.py
bugfix such that status, kill, ....  works. -c is no longer the same as --submit  but the same as --command.
To fix  --xml need to see the config file.
> bugfixed multicrab.py

- common/include/ReconstructionHypothesisDiscriminators.h
- common/src/ReconstructionHypothesisDiscriminators.cxx
* added some functionalities to Chi2Discriminator* classes in common/\*/ReconstructionHypothesisDiscriminators.\*:
* made gaussian chi2 parameters configurable (default kept the same)
* changes are intended to be backward-compatible (no change in the default behaviour)
> updated common/ReconstructionHypothesisDiscriminators

- common/src/JetCorrections.cxx
- core/plugins/NtupleWriter.cc
- core/plugins/NtupleWriter.h
- core/plugins/NtupleWriterJets.cxx
- core/plugins/NtupleWriterJets.h
- core/plugins/PATElectronUserData.cc
- core/plugins/PATMuonUserData.cc
- core/python/ntuplewriter.py
This is a first version of the ntuplewriter running on 76 MC samples. The settings are not yet final. For instance, I just took the latest 76 global tags since there is no official recommendation for GTs yet.
> first running version on 76 MC

- BuildFile.xml
- common/include/ElectronIds.h
- common/src/ElectronIds.cxx
- core/include/Electron.h
- core/include/RecParticle.h
- core/include/SUHH2core_LinkDef.h
- core/plugins/NtupleWriter.cc
- core/plugins/NtupleWriterLeptons.cxx
- core/plugins/NtupleWriterLeptons.h
- core/src/classes_def.xml
New variables for electrons related to HEEP cut
> Electron ID new vars

- core/include/Electron.h
> remove typedef

- common/include/MCWeight.h
- common/src/MCWeight.cxx
> systematic uncertainties in PUWeight

- common/include/CleaningModules.h
- common/include/JetCorrections.h
- common/src/CleaningModules.cxx
- common/src/CommonModules.cxx
- common/src/JetCorrections.cxx
- common/test/TestJetLeptonCleaner.cpp
- common/test/TopJetId.cpp
- common/test/test_JLCkey.cpp
- core/plugins/NtupleWriter.cc
- examples/src/ExampleModule.cxx
- examples/src/ExampleModule2.cxx
- examples/src/ExampleTTbarRec.cxx
Same as PR #333 (implementation of TopJetCleaner in ntuplewriter and SFrame) for master branch
> Topjet clean dev master

- common/include/CleaningModules.h
- common/include/JetCorrections.h
- common/src/CleaningModules.cxx
- common/src/CommonModules.cxx
- common/src/JetCorrections.cxx
- common/test/TestJetLeptonCleaner.cpp
- common/test/TopJetId.cpp
- common/test/test_JLCkey.cpp
- core/plugins/NtupleWriter.cc
- examples/src/ExampleModule.cxx
- examples/src/ExampleModule2.cxx
- examples/src/ExampleTTbarRec.cxx
as #333 but without change of the NtupleWriter for the RunII_25ns_v2 branch
> Implement TopJetLepton cleaning and change JetCleaner and TopJetCleaner

- common/src/MCWeight.cxx
fixed bug that produced seg fault if no sys_up/_down pu file was provided
> Fixed bug in MCPileupReweight

- .gitignore
- common/include/JetCorrections.h
- common/src/JetCorrections.cxx
- common/test/test_JER.cpp
- common/test/test_JER.xml
- common/test/test_JLCkey.cpp
> porting of PR #342 to RunII_76X_v1

- .gitignore
- common/include/JetCorrections.h
- common/src/JetCorrections.cxx
- common/test/test_JER.cpp
- common/test/test_JER.xml
- common/test/test_JLCkey.cpp
> porting of PR #342 to master

- core/python/ntuplewriter.py
added trigger filters for two single-lepton HLT paths:
* HLT_IsoMu27_v\* ["hltL3crIsoL1sMu25L1f0L2f10QL3f27QL3trkIsoFiltered0p09"]
* HLT_Ele27_eta2p1_WPLoose_Gsf_v\* ["hltEle27WPLooseGsfTrackIsoFilter"]
> updated trigger-objects input in ntuplewriter.py

- core/python/ntuplewriter.py
> porting of PR #349 to master

- common/include/CommonModules.h
- common/include/GenJetsHists.h
- common/include/JetIds.h
- common/include/TopJetIds.h
- common/src/CommonModules.cxx
- common/src/GenJetsHists.cxx
- common/src/JetHists.cxx
- common/src/JetIds.cxx
- common/src/TopJetIds.cxx
Some additions to the code as described in the commit messages. should hopefully not corrupt any code
> Run ii 25ns v2

- common/include/CommonModules.h
- common/include/GenJetsHists.h
- common/include/JetIds.h
- common/include/TopJetIds.h
- common/src/CommonModules.cxx
- common/src/GenJetsHists.cxx
- common/src/JetHists.cxx
- common/src/JetIds.cxx
- common/src/TopJetIds.cxx
cherry-pick from RunII_25ns_v2
> Run ii 76 x v1

- common/include/CommonModules.h
- common/src/CommonModules.cxx
backporting a feature already present in RunII_76X_v1
> PU systematics switch in CommonModules

- common/include/MCWeight.h
- common/src/MCWeight.cxx
forward port of 508245d7f4230cded87abc96eb1251204c42b369
> add possibility to set name postfix for stored btag weights

- common/include/TopPtReweight.h
- common/src/TopPtReweight.cxx
code is comming from VLQ preselection repo, with small changes.
> top pt reweighting is needed in several analysis

- common/src/CommonModules.cxx
see https://twiki.cern.ch/twiki/bin/view/CMS/MissingETOptionalFiltersRun2#MiniAOD_805
> new recommendation for MET filters

- core/python/ntuplewriter.py
First changes that we will need for our next ntuple production round.
> new MET filters and option to run on reHLT trigger menu

- common/include/BTagCalibrationStandalone.h
- common/include/MCWeight.h
- common/src/BTagCalibrationStandalone.cc
- common/src/MCWeight.cxx
> hide debug printout

- common/include/MCWeight.h
- common/src/MCWeight.cxx
For example  for muon efficiency (HLT data based)
> add parameter to handle rotated hists

- common/src/JetCorrections.cxx
following JetMETCorrections/Type1MET/interface/PFJetMETcorrInputProducerT.h
> MET Type1 correction

- common/src/JetCorrections.cxx
- core/include/Jet.h
- core/include/MET.h
- core/plugins/NtupleWriter.cc
- core/plugins/NtupleWriterJets.cxx
- core/python/ntuplewriter.py
add slMETsCHS collection
add uncorrected MET variables
store L1 factor for JEC (needed for MET correction)
Result for JEC application and corresponding MET correction consistent with cms-jet/JMEReferenceTable results.
> JEC propagation to MET

- common/include/JetIds.h
- common/src/JetIds.cxx
according to https://twiki.cern.ch/twiki/bin/viewauth/CMS/JetID
> Updated JetPFID

- common/include/MCWeight.h
- common/src/MCWeight.cxx
> Tau ID SF slightly changed; BTagging recommendations slightly changed

- scripts/crab/DasQuery.py
uses the proxy, no password is needed anymore. check if something is found
> use new das_client

- scripts/crab/CrabScript.py
- scripts/crab/multicrab.py
> crab scripts

- scripts/readaMCatNloEntries.py
this way the result of the script is directly stored in the xml file. 
can be retrieved later on with sframe_batch if one wants to
> add tag to the end of xml file!

- core/src/AnalysisModuleRunner.cxx
checks if all objetcs written to the output tree have been assigned a correct value during the process routine
> check output

- common/include/CommonModules.h
- common/include/JetCorrections.h
- common/src/CommonModules.cxx
- common/src/JetCorrections.cxx
- common/test/TestJetCorrections.cpp
- common/test/test_JER.cpp
- common/test/test_JLCkey.cpp
- scripts/install.sh
Detailed E-mail with instructions following
> Moriond17 jec

- core/src/UniversalGenJetCluster.cxx
- scripts/crab/readaMCatNloEntries.py
Das lesen der Gewichte wird noch ziemlich lang dauern. Deswegen hier schon einmal die anderen Aenderungen. Vor allem, weil hier auch der Fix von Daniel fuer das 'readaMCatNloEntries' enthalten ist.
> Run ii 80 x v3

- scripts/create-btag-effiency-histos.py
produce AK4 btag hists nothing changed
produce AK8 btag hists change folder='' to folder='AK8' for subjet b tagging
>  AK8 btag hists can be produced

- core/include/GenInfo.h
- core/plugins/NtupleWriter.cc
(to directly veto events if the pt-hat of the PU is bigger than the pt-hat of the hard scattering)
> Add max pt-hat for PU

- core/python/ntuplewriter_EGammaReg.py
Add EGamma regression and smearing, re-correct MET based on e/gamma gain switch correction on the fly for Re-Miniaod Data
> Add EG regression and re-correct MET

- core/python/ntuplewriter.py
> fix bug with chsMET

- core/python/ntuplewriter_EGammaReg_woMETonFly_MC.py
With chsMET fixes and without EGamma on-fly correction on MET (it does not work anyway)
> add config for JERC MC ntuples

- common/src/TTbarGen.cxx
- examples/config/ExampleTTbarGen.xml
this commit is also part of RunII_80X_v3
> more robust TTbarGen class

- core/include/Event.h
- core/include/EventHelper.h
- core/src/AnalysisModuleRunner.cxx
- core/src/Event.cxx
- core/src/EventHelper.cxx
- core/src/classes.h
Some basic book keeping to add a TopPuppiJetCollection to the SFrame config
> Added Puppi TopJet Collection

- core/plugins/NtupleWriter.cc
- core/python/ntuplewriter_92X.py
add access to trigger prescales with 92X miniAOD and switch off TopJet to process 2017 data
> 2017 data processing

- common/include/JetCorrections.h
- common/src/JetCorrections.cxx
Hey Thomas,
Just added the JECs for AK4 and AK8 Puppi jets. Hopefully this pull request is not controversial.
Doug
> Added JECs for Puppi AK4 and AK8 jets

- core/plugins/PATElectronUserData.cc
- core/python/ntuplewriter.py
- scripts/install.sh
modified install.sh script and ntuplewriter to store the effective are of electrons, which is used in the calculation of the electron's isolation.
> Enabled AEff calculation for electrons in ntuplewriter.py

- common/src/JetCorrections.cxx
At the last commit I overlooked some debug output from me.
> cleaned up more debug output

- common/datasets/RunII_80X_v3/DATA_SinglePhoton_Run2016B_03Feb.xml
- common/include/JetCorrections.h
- common/src/JetCorrections.cxx
Remove empty file from SinglePhoton RunB, add tmp corrections for JERC studies
> sync changes

- common/src/CommonModules.cxx
> [94X] Update MET filters

- common/include/JetCorrections.h
- common/src/JetCorrections.cxx
Hi, 
I included the paths to the newest Jet correction (that I am aware of).
> re-added 03Feb17 correction pathes into the JERFiles

- common/src/JetCorrections.cxx
> overlooked the smearing

- scripts/install.sh
This is the same as #814 but for master branch
> [master] Install SFrame in main install.sh script

- core/python/ntuplewriter.py
This is only formatting & refactoring changes (& to make it easier on my eyes when staring at it 😵 ). In some places this means adding some variables to ensure module/collection names can't get screwed up.
I have taken the `addJetCollection` mods from #813 and put them into a function since we use it all over the place. 
I have also turned off the XCONE & HOTVR collections, since they weren't producing anything anyway.
> [94X] Tidy up formatting of ntuplewriter.py

- core/include/Jet.h
- core/plugins/NtupleWriterJets.cxx
- core/python/ntuplewriter.py
> Hbb moriond18

- common/include/JetIds.h
- common/src/JetIds.cxx
> DeepCSV WPs

- common/datasets/MC_94X_v1/TEMPLATE_CONFIG_QCD_Pt-15to7000.xml
- common/datasets/RunII_94X_v1/TEMPLATE_CONFIG_JetHT_RunB_17Nov17_v1.xml
- common/datasets/RunII_94X_v1/TEMPLATE_CONFIG_JetHT_RunC_17Nov17_v1.xml
- common/datasets/RunII_94X_v1/TEMPLATE_CONFIG_JetHT_RunD_17Nov17_v1.xml
- common/datasets/RunII_94X_v1/TEMPLATE_CONFIG_JetHT_RunE_17Nov17_v1.xml
- common/datasets/RunII_94X_v1/TEMPLATE_CONFIG_JetHT_RunF_17Nov17_v1.xml
as asked for by Anastasia in #826
> deleted TEMPLATE files of the data/MC configs

- core/include/MET.h
- core/plugins/NtupleWriter.cc
Old name implied it was corrected, definitely isn't. More suitable @karavdin ?
> [94X] Rename CHS MET variable

- common/include/JetCorrections.h
> corrected typo

- core/python/ntuplewriter_woHOTVR_woXCONE.py
- core/python/ntuplewriter_woHOTVR_woXCONE_MC.py
samples for JEC related studies produced without HOTVR and XCONE  due to lack of tims
> configs for production without HOTVR and XCONE

- common/include/JetCorrections.h
- common/src/JetCorrections.cxx
added 17Nov2017 L1RC JERC pathes
> Run ii 94 x v1

- core/python/ntuplewriter_woHOTVR_woXCONE.py
- core/python/ntuplewriter_woHOTVR_woXCONE_MC.py
update wo HOTVR and XCONE scripts to be inline with common ntuplewriter.py
> update wo HOTVR and XCONE scripts 

- common/src/MCWeight.cxx
These events have TrueNumInteractions that fall outside the hist limits, e.g. if -ve. Not thrown error as probably want to continue processing, but have issued warning.
Needed as already seen MC sample with TrueNumInteractions = -30000
> [94X] Add protection for MC events with bad TrueNumInteractions

- examples/Makefile
With this update, the create-new-analysis compiles again
> Updated example/Makefile

- common/include/JetCorrections.h
- common/src/JetCorrections.cxx
> updated JEC

- scripts/crab/DasQuery.py
- scripts/crab/test_DasQuery.py
Since the depreciation of das_client.py, DasQuery.py must be updated. I've used the builtin wrapper in CMSSW, https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_24/Utilities/General/python/cmssw_das_client.py, to facilitate this. The result for the end user running multicrab, etc should be fully transparent.
I've also added a little test script to check it actually does what it should.
I'll do separate PRs for 80X and 94X branches.
> Fix DasQuery.py [master]

- scripts/crab/DasQuery.py
- scripts/crab/test_DasQuery.py
> Fix DasQuery.py [80X]

- scripts/crab/DasQuery.py
- scripts/crab/test_DasQuery.py
> Fix DasQuery.py [94X]

- core/python/ntuplewriter.py
> Add doAllGenParticlesPythia8 to ntuplewriter py config [80X_v4]

- core/python/ntuplewriter.py
> Add doAllGenParticlesPythia8 to ntuplewriter py config [master]

- common/include/JetCorrections.h
- common/include/Utils.h
- common/src/JetCorrections.cxx
re-enabled V6 MC JEC
added option for thresholds in the MET correction
> updated JEC and MET correction

- scripts/crab/DasQuery.py
- scripts/crab/test_DasQuery.py
Copy of #902 for the 80X_v4 branch
> [80X_v4] Fix DasQuery.py

- common/src/TTbarGen.cxx
Added a workaround fix for the rare issue that no b or W daughter is found due to the top having more than two daughters, or more precisely: There may be more genparticles than just b and W which reckon the top as mother, e.g. two leptons coming from a photon that radiated off the top. Consequently, the runtime_errors are de-commented again. If the runtime_errors ever occur again, there will be indeed no b and W daughters and the MC sample will have to be investigated further.
Copy of #884 to 80X_v4
> Copy of "More robust b/W daughter identification in TTbarGen" from #884 in 80X_v3

- common/test/TestTriggerSelection.cpp
- common/test/Trigger.xml
Looks for `Flag_*` and `HLT_*` in trigger list. Throws error if not the case.
> [80Xv5] Add test to explicitly check both HLT and MET flags in list of triggers

- scripts/crab/DasQuery.py
- scripts/crab/test_DasQuery.py
> [80Xv4] Fix issue with duplicate datasets from DasQuery, update tests

- scripts/crab/DasQuery.py
- scripts/crab/test_DasQuery.py
> [80Xv3] Fix issue with duplicate datasets from DasQuery, update tests

- scripts/crab/DasQuery.py
- scripts/crab/test_DasQuery.py
> [94X] Fix issue with duplicate datasets from DasQuery, update tests

- core/plugins/HOTVRProducer.cc
- core/plugins/NtupleWriter.cc
- core/plugins/XConeProducer.cc
- core/python/ntuplewriter.py
- core/src/UniversalGenJetCluster.cxx
Does PseudoXcone, modify XCone params, fix subjet linking, fix leptons in GenXcone23
> [master] XCone/HOTVR fixes back propagate to master

- scripts/crab/crab_template.py
Otherwise it gives ext1 and ext2 datasets with same request name
same as #942 but for master
> [master] Better ext in crab requestName

- scripts/crab/crab_template.py
Otherwise it gives ext1 and ext2 datasets with same request name
> [80Xv5] Better ext in crab requestName

- scripts/create-multi-dataset-xmlfiles.py
With this change only root files with at least 1 event are added to the xml file. It prevents many crashes.
> now the root file is added in the dataset xml only if it has n_events > 0

- common/include/JetCorrections.h
- common/src/JetCorrections.cxx
> JEC Fall17_V13 for data

- core/plugins/HOTVRProducer.cc
- core/plugins/XConeProducer.cc
- core/python/ntuplewriter.py
> [master] Missing XCone & HOTVR updates

- common/test/test_JER.cpp
- common/test/test_JLCkey.cpp
- core/include/AnalysisModuleRunner.h
- core/python/ntuplewriter.py
- Fix path to avoid silly HEEP errors in config
- Some fixes to remove more compilation warnings (yay)
- Add missing headers from introducing `JetCorrectionSets.h`
> [master] More missing fixes

- common/src/MCWeight.cxx
Reverts UHH2/UHH2#978
The formatting has gone haywire, needs to be redone properly with only the logic changes
> Revert "bug fixed"

- common/src/MCWeight.cxx
> [master] Port of #980

- common/src/JetCorrections.cxx
corrected typos in the JetCorrections.cxx macro
> corrected typos in JetCorrections.cxx

- scripts/crab/commentOutEmptyNtuples.py
- scripts/crab/readaMCatNloEntries.py
see *documentation* in code for further details
> add python script to get rid of empty ntuples in dataset xmls

- common/include/CommonModules.h
- common/src/CommonModules.cxx
- common/src/JetCorrections.cxx
remove JER smearing from L1offset in correct_MET, add flag for CHS MET in common modules
> few changes for TypeI MET 

- core/src/Event.cxx
- scripts/create-multi-dataset-xmlfiles.py
- scripts/install.sh
- scripts/testDatasetXML.py
This copies across Andrea's fixes to trigger & XML creation. Also adds in some of my own minor fixes/features.
Also the 1000th PR! 🎉
> [master] Cherrypick fixes from 94X, and some other fixes

- core/src/Event.cxx
- scripts/create-multi-dataset-xmlfiles.py
- scripts/install.sh
- scripts/testDatasetXML.py
> [101] Cherrypick fixes from 94X, and some other fixes

- core/plugins/GenHOTVRProducer.cc
- core/plugins/GenXConeProducer.cc
- core/plugins/NtupleWriter.cc
- core/plugins/NtupleWriter.h
- core/plugins/XConeProducer.cc
- core/python/ntuplewriter.py
This moves the GenHOTVR and GenXCone clusterers into their own modules, out of UniversalGenCluster and Ntuplewriter. It also allows more flexibility in future with regards to inputs/configuration, and fewer bottlenecks when running multicore.
All the previous functionality is the same except:
- I have removed the softdrop mass from genxcone as (a) it wasn't being used, (b) it requires more work to setup correctly to get the subjets. Let me know if you want it back in, it can be done.
- The GenXConeProducer has the ability to find the highest pt lepton, and reduce the NJets by 1 for the jet closest to the lepton (as before), except now it isn't hardcoded for NJets=3, and you can also set a maximum DeltaR for a lepton to be considered matched to a jet.
One question though for @denschwarz, …
> [80v5] GenHOTVR/XCone producers

- scripts/install.sh
> [101_v1] Update install script for HOTVR + other niceties

- scripts/install.sh
> [94_v2] Update install script for HOTVR + other niceties

- core/plugins/GenHOTVRProducer.cc
- core/plugins/GenXConeProducer.cc
- core/plugins/NtupleWriter.cc
- core/plugins/NtupleWriter.h
- core/plugins/XConeProducer.cc
- core/python/ntuple_generator.py
Port of #962 for 101_v1 branch
> [101_v1] Port of generator XCone & HOTVR

- core/plugins/GenHOTVRProducer.cc
- core/plugins/GenXConeProducer.cc
- core/plugins/NtupleWriter.cc
- core/plugins/NtupleWriter.h
- core/plugins/XConeProducer.cc
- core/python/ntuplewriter.py
> [94v2] Port of generator XCone & HOTVR

- scripts/install.sh
> [94X_v1] Update install script for HOTVR + other niceties

- core/include/Jet.h
- core/plugins/GenXConeProducer.cc
- core/plugins/NtupleWriter.cc
- core/plugins/XConeProducer.cc
- core/python/ntuplewriter_addL1seed_woHOTVR_woTopJets_wTriggerObjects_wLowPtjets_wXCONE_wGenParticles_MC.py
works on 1e3 QCD events, to be checked on ~1e7 events
> don't add dummy jets to avoid issues with sub-jet clustering

- common/include/JetCorrections.h
- common/src/JetCorrections.cxx
I forgot, that I had to change the filenames for DE combined...
> V31 in JetCorrections now with DE combined

- Makefile.common
- core/include/AnalysisModuleRunner.h
- core/include/obj.h
- core/include/registry.h
- core/src/AnalysisModuleRunner.cxx
- scripts/install.sh
Move to CMSSW_10_2_6, latest version. Also move to C++17 & GCC7, and fixes to make code compile under GCC7.
> [102X] Setup install script, fixes for C++17

- scripts/install.sh
> [102X] Use correct branch; remove redundant addpkg

- common/src/JetCorrections.cxx
> [102X] Port: Fixed critical bug in type-1 correction of Puppi-MET

- common/src/JetCorrections.cxx
> [94Xv2] Port: Fixed critical bug in type-1 correction of Puppi-MET

- common/src/JetCorrections.cxx
> [94Xv3] Port: Fixed critical bug in type-1 correction of Puppi-MET

- scripts/crab/DasQuery.py
- scripts/crab/crab_template.py
- scripts/crab/makeCheckCrabTarball.py
Add small script to crate tarball as CRAB would, and optionally check the size.
Allows us to check we have sensible tarball sizes for CRAB jobs before submitting a load of CRAB jobs.
> [102X] CRAB tarball creator & checker, updates to DasQuery

- core/python/ntuplewriter_data_2016v2.py
- core/python/ntuplewriter_data_2016v3.py
- core/python/ntuplewriter_data_2017.py
- core/python/ntuplewriter_data_2018.py
- core/python/ntuplewriter_mc_2018.py
Use 03Feb2017 files for data 2016v2
> [102X] Update example files in 2016v2 data cfg

- scripts/crab/DasQuery.py
- scripts/crab/crab_template.py
- scripts/crab/makeCheckCrabTarball.py
> [94Xv1] CRAB tarball checker + changes for testing

- scripts/install.sh
> [94Xv1] Remove .git from EGamma external files as inflates CRAB tarball

- core/python/ntuple_generator.py
Remove duplicate triggers
also more frequent printout for logging
> [102X] Cleanup trigger obj in ntuple

- core/include/GenTopJet.h
- core/plugins/NtupleWriter.cc
Simplify the code for charged/neutral component calculation to make it general and generator independent.
> [102X] simplify  charged/neutral component calculation

- core/python/ntuple_generator.py
Only stores pt, phi, sumET. Not sure if other variables of interest?
> [102X] Add in GenMet for MC samples

- core/plugins/GenHOTVRProducer.cc
- core/plugins/GenXConeProducer.cc
Unable genjet constituences storage for HOTVR jets, as in https://github.com/UHH2/UHH2/pull/1103
Use proper vertex info for HOTVR and XCONE jets.
> [102X] copy modifications for GenXCONE to GENHOTVR

- core/plugins/NtupleWriter.cc
- core/plugins/NtupleWriter.h
- core/python/ntuple_generator.py
fill gen energy fractions for self-clustered gentopjet, add flag to switch storing of genjet constituents on/off
> [102X] fix energy fractions for gen.topjets, flag for genjet constituents

- core/python/ntuple_generator.py
List of triggerObjects for Z'->ttbar HLT paths obtained from [1] and [2].
[1] https://raw.githubusercontent.com/UHH2/TriggerPaths/master/hlt_2016_v4.2_V8.py
[2] https://raw.githubusercontent.com/UHH2/TriggerPaths/master/hlt_2018_v3.6_V4.py
> [102X] add trigger objects for Z'->ttbar triggers

- core/include/Jet.h
Changed to -1 as 0 is a valid index
> [102X] Change default value of m_genjet_index, add getter for genjet_index

- core/plugins/GenHOTVRProducer.cc
- core/plugins/GenXConeProducer.cc
- core/plugins/HOTVRProducer.cc
- core/plugins/NtupleWriter.cc
- core/plugins/XConeProducer.cc
Create pat jets for reco XCONE and HOTVR in similar way like it's done for genjets. Also linking to constituents is fixed for reco and gen XCONE and HOTVR jets.
> [102_X] Proper pat jets for RECO xcone and hotvr

- core/python/ntuple_generator.py
Now we can relatively easily rename our jet collections by using new function `rename_module`. This can also handle userData (e.g. for `PATJetUpdater` modules) so that e.g. PUPPI multiplicities are not broken (because we use the collection name to lookup the userFloat)
All AK{4,8}{CHS,PUPPI} collections have been renamed, except `slimmedJets` since we don't touch it. But we can rename that as well to `jetsAk4CHS` for consistency.
So we now have:
Jets: `slimmedJets`, `jetsAk4Puppi`, `jetsAk8CHS`, `jetsAk8Puppi`  (the latter 2 are the low-pT ones for JERC)
TopJets: `jetsAk8CHSSubstructure_softDropCHS`, `jetsAk8PuppiSubstructure_softDropPUPPI`
Are the new names OK? Or do we also want something in them to reflect whether we have reclustered them?
> [102X] Better Jet/TopJet collection names

- core/python/ntuple_generator.py
Adding MET collection ("slMETsCHS") with explicit clustering of CHS MET for 2016 data and MC, for which chs MET user-floats were not available
> [102X]  add CHS MET for 2016 data

- README.md
- common/include/BTagCalibrationStandalone.h
- common/include/MCWeight.h
- common/src/BTagCalibrationStandalone.cc
- common/src/MCWeight.cxx
propagate method for b-tagging systematic from 94X_v1 @reimersa private brunch
> [102X] Add b-tagging shape systematic for CSV

- core/plugins/NtupleWriter.cc
- core/plugins/NtupleWriter.h
- core/plugins/NtupleWriterJets.cxx
- core/plugins/NtupleWriterJets.h
- core/python/ntuple_generator.py
> Revert "[102X] add more flags for PF/GEN constituents storing"

- core/python/ntuple_generator.py
Two lists are created from stable GenParticles:
1. muons and photons that have a muon as a mother
2. electrons and photons that have electrons as a mother
These lists are then used as input for anti-kT clustering with R=0.1
Note: In Herwig++ the jets will not have photons included. But for the samples where this is actually used (2016 version of ttbar Powheg and aMC@NLO) it works.
> added Muon and Electron GenJets

- common/include/JetIds.h
- common/src/CommonModules.cxx
- common/src/JetIds.cxx
- common/test/test_JER.cpp
- common/test/test_JLCkey.cpp
Add JetID for 2016/2017/2018 together, set up working points for CHS and PUPPI
[onlycompile]
> [102X] update JetID cuts

- common/src/JetIds.cxx
> [102X] fix silly mistake in 2018 JetID

- common/datasets/RunII_102X_v1/DATA_Run2018D_JetHT_TEST.xml
JetHT Run2018D v2 with PF jet constituents of 4 leading jets for JER/JEC analysis tests
[ci skip]
> [102X] JetHT Run2018D for tests

- examples/config/ExampleJetComposition.xml
- examples/config/ExampleJetConstituents.xml
- examples/src/ExampleHists.cxx
- examples/src/ExampleJetComposition.cxx
Starting point for examples of jet composition/constituents. Will be updated and polished in the future
[only compile]
> [102X] tmp of examples for jet composition checks

- core/python/ntuplewriter_mc_2018_allConstits.py
Splitting up #1190 since I want to also test if my changes there work, so only add the config for now
[only compile] since it got tested last time
> [102X] Add cmssw config to run with all jet constituents stored

- core/include/TopJet.h
> [102X] add functions to calculate raw scores of DeepBoosted tagger

- examples/config/ExampleJetConstituents.xml
- examples/src/ExampleModuleJetConstituents.cxx
> [102X] Do original vs reco check for subjets of (Gen)TopJets in ExampleJetConstituents

- common/include/NSelections.h
- common/src/CommonModules.cxx
> add Selection for recalculated metfilter related to ecalBadCalib

- core/python/ntuple_generator.py
Don't believe these are used. Make negligible saving to time etc, just tidying up.
> [102X] Remove unused btagging algos

- core/plugins/GenXConeProducer.cc
- core/python/ntuplewriter_mc_2018_dijet.py
* switch off addition of dummy xcone genjets
* add config for dijet samples
> [102X] switch off addition of dummy xcone genjets

- scripts/crab/crab_template.py
> [10_2_X] increase requested RSS

- scripts/install.csh
Hey Robin and Anastasia,
I added a csh version of the installation script.
Doug
> Added at csh version of the script

- common/src/TTbarGen.cxx
from #884 in 80X_v3
[only compile]
> [102X] copy of TTbarGen fix from 80X_v3 

- common/src/CommonModules.cxx
- core/python/ntuple_generator.py
- Disable Bad Charged Candidate Filter in 2016v2 config as now not recommended
- Add `Flag_eeBadScFilter` in CommonModules, only used for data
> [102X] More MET filter updates

- examples/config/Example.xml
- examples/config/Example2.xml
- examples/config/ExampleComposing.xml
- examples/config/ExampleEGammaID.xml
- examples/config/ExampleEventInput.xml
- examples/config/ExampleEventInput2.xml
- examples/config/ExampleEventOutput.xml
- examples/config/ExampleJetComposition.xml
- examples/config/ExampleJetConstituents.xml
- examples/config/ExampleJetTags.xml
- examples/config/ExampleMuonID.xml
- examples/config/ExampleTTbarGen.xml
- examples/config/ExampleTTbarRec.xml
- examples/config/ExampleTrigger.xml
- examples/config/GenParticlesPrinter.xml
- examples/config/MakePileupHistMC.xml
- year in Version attribute
- collections names brought up to date
- general tidying up
[ci skip]
> [102X] Update example configs
