common/include/ElectronHists.h
common/include/MuonHists.h
common/src/MuonHists.cxx

I switched the default filling of the gen-plots to true. However, if the genparticles collection is not available, they will simply not be filled.

gen-histos for electrons as well; default: true

---

core/plugins/NtupleWriter.cc

This created an error at runtime because reco::BasicJetCollection is already a std::vector<reco::BasicJet>

wrong consumes requirement on gentopjets

---

common/include/JetCorrections.h
common/src/JetCorrections.cxx

I added a SubJetCorrector class similar to (Top)JetCorrector.
Preliminary studies show that it may be needed to correct subjets at 13TeV
The behavior is similar to UHHAnalysis subjet recorrector:
1) It is not needed to uncorrect the subjets because the ntuplewriter corrects the subjets at level 0, that is: they're not corrected.
2) However the subJEC_raw value is set to the full correction, thus by uncorrecting we would un-apply a correction that was never applied in the first place.
3) The analyzer then must be careful to apply subjet JECs only *once* in the entire analysis.

SubJetCorrector added

---

common/include/JetCorrections.h
common/src/JetCorrections.cxx

This commit adds the Generic*JetCorrector classes that allow to correct (Top,Sub)Jets collections obtained from handles.
In principle, to avoid the uncontrolled proliferation of corrector classes, one could merge these classes with the standard ones by overloading the constructor with some bogus default values for the additional parameters.
The "process" method would then check the validity of the values of the additional parameters and decide whether to correct the standard collection or the "handle".
I don't know whether that would be cleaner / more efficient. It depends on how widespread is the use-case of correcting "Handle" Jet collections (probably rather uncommon, apart from jet tagging studies).

correctors for jet collections obtained from handles

---

common/include/ElectronHists.h
common/include/EventHists.h
common/include/HypothesisHists.h
common/include/JetHists.h
common/include/MuonHists.h
common/include/TauHists.h

Make the private members in hist classes in common module (e.g. EventHists, ElectronHists, etc.) protected; this way one can make his own hist class inheriting from these hist classes and is able to manipulate inherited members of the mother hist classes.

Make private members in hist classes protected

---

common/src/TopJetIds.cxx

* change in the definition of the "CMS-Top-Tagger" ID
* current version uses groomed mass (mass of sum of subjets p4)
* Zprime semileptonic analysis at 8TeV used ungroomed mass (following approach in JME-13-007 and Z' all-hadronic analysis)
* reverting to ungroomed mass and pushing this change centrally (as discussed w/ Thomas Peiffer)
* this change can be propagated to 'next-ntuple-format' branch

moved to ungroomed mass in CMSTopTag ID

---

common/include/GenTools.h
common/include/ObjectIdUtils.h
common/include/Utils.h
common/src/GenTools.cc

Expanded functionality in GenTools module but that should not affect anyone.
Main changes are:
* Adding an OrId in ObjectIdUtils so that one can now also look for the logical 'Or' of different Ids (e.g. useful for GenParticleIds)
* Overloading the sort_by_pt() function in the Utils module so that can now also run on a vector of pointers (useful if one wants to create his own Particle collection and sort it but does not want to copy all the particles from the original collection)

Few minor changes

---

common/datasets/MC_LQ_TMu_M700_20x25.xml
common/datasets/MC_LQ_TMu_M900_20x25.xml

Some jobs were crashing when producing the miniAODs for LQtoTopMuon. Hence, some (many) events were missing after ntuplelisation. Missing events are added now

correction for some LQtoTMu xml files

---

common/include/Utils.h
common/src/Utils.cxx

move implementation of "safe inv. mass" method to src/Utils.cxx
* removed body of non-templated function from header file (avoids multiple copies of the function and a bunch of warnings)
* minor renaming to make content clearer

moved implementation of safe-inv-mass method to src/

---

common/include/ReconstructionHypothesis.h
common/include/ReconstructionHypothesisDiscriminators.h
common/src/ReconstructionHypothesisDiscriminators.cxx
common/src/TTbarReconstruction.cxx

* addition of an alternative chi2-discriminator (in ReconstructionHypothesisDiscriminators), to be used for events with a top-tagged jet
* hadronic term of the chi2 calculated using the groomed (instead of ungroomed) topjet mass
* added a pointer to TopJet as data member of the ReconstructionHypothesis class, in order to be able to access TopJet-specific methods (e.g. subjets)

addition of a ttbar-chi2 discriminator for top-tagged events

---

common/include/ElectronIds.h

* added kinematic selector for electrons, cutting on pt and |supercluster_eta| (instead of the standard pseudo-rapidity)

added selector for electrons (pt + supercluster_eta)

---

common/src/TauIds.cxx
core/include/AnalysisModule.h
core/plugins/NtupleWriter.cc
core/src/AnalysisModuleRunner.cxx

declaring and implementing Context::undeclare_event_output(string), to remove branches from output.
Implementation in CMSSWContext simply throws a runtime exception.

undeclare event output

---

common/include/EventShapeVariables.h
common/src/EventShapeVariables.cxx

The class in PhysicsTools/CandUtils/interface/EventShapeVariables.h is ported to sframe. We decided to copy the code and modify it according to our needs. It might have been possible to interface the original code, but the dependency on DataFormats/Candidate (only by one of the Constructors, actually) would have introduced a lot of unneeded code from cmssw into sframe.

event shape variables

---

common/include/CollectionProducer.h

These are two tools related to tagging and applying id-functions to objects. 
CollectionProducer makes a new collection (see the example for b-jets).
CollectionSizeProducer makes an int, the number of tagged objects in the given collection.

collection producer

---

core/python/ntuplewriter.py

The ntuplewriter.py script is now running on a run 2 MC sample. There are still some open issues:
Only jets stored in MINIAOD are taken. Running of new jet clustering algorithms is not yet working (most probably due to b-tagging).
The electrons are using a Phys14 ID, but there is no later electron ID available on the twiki page https://twiki.cern.ch/twiki/bin/viewauth/CMS/CutBasedElectronIdentificationRun2
In MINIAOD, there are some "subjet" collections ("slimmedJetsCMSTopTagCHSPacked", "slimmedJetsAK8PFCHSSoftDropPacked"). They seem to be incompatible with our NtupleWriter because their format is not a standard std::vector<pat::Jet>.
All other collections seem to work but it has to be checked that they are identical with the B2GAnaFW.

first attempt to get the ntuplewriter running on run 2 samples

---

core/include/Muon.h

This fix is required for root 6. Otherwise, the member variables of the muon are not stored when running the NtupleWriter.

add dummy member to enum in Muon.h

---

core/plugins/NtupleWriterLeptons.cxx

fixed the variable used for the electron "number-of-missing-hits" (which enters the electron cut-based ID), in order to match the definitions used in the Egamma POG
* refs
* https://hypernews.cern.ch/HyperNews/CMS/get/recoTracking/1459.html
* https://github.com/ikrav/cmssw/blob/egm_id_phys14/RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleMissingHitsCut.cc#L38 (found after some browsing of https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2)

fixed electron variable (missing-hits) in "NtupleWriterLeptons" plugin

---

core/include/Electron.h
core/include/Muon.h
core/plugins/BuildFile.xml
core/plugins/CandIsolatorFromDepositsMINIISO.cc
core/plugins/CandIsolatorFromDepositsMINIISO.h
core/plugins/NtupleWriterLeptons.cxx
core/plugins/PATElectronUserData.cc
core/plugins/PATMuonUserData.cc
core/plugins/PFCandIsolatorFromDepositsMINIISO.cc
core/plugins/PFCandIsolatorFromDepositsMINIISO.h
core/plugins/convertPackedCandToPFCand.cc
core/python/electron_pfMiniIsolation_cff.py
core/python/muon_pfMiniIsolation_cff.py
core/python/ntuplewriter.py
core/python/pfCandidatesByType_cff.py
env.sh

* addition of some variables for lepton reconstruction
* mini-isolation
* muon medium-ID
* electron MVA
* important: updates tested in CMSSW_7_4_3 (on top of the compilation instructions in the UHH2/ twiki)
* mini-isolation:
* mini-isolation deposits are calculated using 2 plugins (located in core/plugins/):
* MUONS: plugin="CandIsolatorFromDepositsMINIISO": minimal generalization of the standard plugin "PhysicsTools/IsolationAlgos/plugins/CandIsolatorFromDeposits.*", which is used for the standard (fixed-cone) calculation of the isolation deposits for muons (see RecoMuon.MuonIsolation.muonPFIsolationValues_cff).
* ELECTRONS: plugin="PFCandIsolatorFromDepositsMINIISO": minimal generalization of the standard plugin "CommonTools/ParticleFlow/plugins/PFCandIsolatorFromDeposit.*", which is …

updates for lepton reconstruction (mini-isolation)

---

common/include/PrimaryLepton.h
common/include/TTbarReconstruction.h
common/src/PrimaryLepton.cxx
common/src/TTbarReconstruction.cxx

I put the PrimaryLepton class into a file on its own because I think it can be used outside of ttbar reconstruction (e.g. for the semi-leptonic VLQ searches) as well and I repeatedly had a hard time to find the definition of this class since it was "hidden" in the TTbarReconstruction header file^^

put PrimaryLepton into own file to make code clearer

---

core/plugins/NtupleWriter.cc

Over concerns that the PFHTForMC trigger path used to emulate PFHT800 might change version across different MC productions I made the code independent the trigger version.

make PFHT800 emulation independent of PFHTForMC version

---

common/include/TopJetIds.h
common/src/TopJetIds.cxx

Adding the option to use the the groomed mass for the CMSTopTagger, the default option isn't changed.
To use the groomed mass use CMSTopTag(CMSTopTag::MassType::groomed).
Generic groomed mass function implemented, used also in the HEPTopTagger class.

Adding groomed mass option for the CMSTopTagger

---

core/plugins/NtupleWriter.cc

Do not fill the systweights if externalLHEProducer is not given.
This fix is needed for pure Pythia samples that are not based on external LHE files.

bugfix for systweights

---

core/plugins/NtupleWriter.cc
core/plugins/NtupleWriterJets.cxx
core/python/ntuplewriter.py

This implements nsubjettiness for all the top jet collections. The structure is as follows:
CMSTopJet --> taken from MINIAOD userfloats
SoftDrop --> calculated from AK8 ungroomed
CA15Filtered --> calculated from CA15 ungroomed
HEPTopJet --> calculated from CA15 ungroomed

nsubjettiness for all jet collections

---

common/include/CommonModules.h
common/include/LumiSelection.h
common/include/LuminosityHists.h
common/src/CommonModules.cxx
common/src/EventVariables.cxx
common/src/LumiSelection.cxx
common/src/LuminosityHists.cxx
common/test/LumiHists.xml
common/test/TestLumiHists.cpp
core/python/myLumiCalc.py

Added tool to create lumifile (myLumiCalc.py).
Added selection module to select only good data events according to lumifile (LumiSelection).
Example how to use the lumifile and LumiSelection can be found in TestLumiHists.cpp.
LumiSelection is automatically called by CommonModules.
Important note: 
If you want to use the LumiSelection in CommonModules, you have to use CommonModules as a selection in your own module. I.e., replace code like
common->process(event);
by
bool pass_common = common->process(event);
if(!pass_common) return false;
in the process routine of your module.

Lumi tools added

---

core/src/AnalysisModuleRunner.cxx

Data are given weight 1 regardless of the sample lumi value (it doesn't have to match the lumi in the cycle block).
It used to be like this in the old UHHAnalysis. It is useful when one wants to run over different data streams, or split big chunks of data.

Force weight=1 for data

---

common/include/ElectronIds.h
common/src/ElectronIds.cxx

* updated working-points for electron cut-based ID (phys14 tuning)
* added routines for ID based on non-triggering MVA
* REFs:
* https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2
* https://twiki.cern.ch/twiki/bin/view/CMS/MultivariateElectronIdentificationRun2

updates for common/ElectronIds [cutbased-ID wps; mva-ID;]

---

core/plugins/NtupleWriter.cc

This should hopefully fix the issue observed in some low energy QCD events where trigger names and trigger results have different size.

more robust PFHT trigger emulation

---

common/include/ReconstructionHypothesis.h

* keep the Jet object in the ttbar-hypothesis container
* useful to access jet variables, e.g. b-tag, in testing methods for the ttbar kinematical reconstruction

save full jet information in common/ReconstructionHypothesis

---

core/python/ntuplewriter.py

I have added a new MET collection (slimmedMETsNoHF) according to the new recipe (see https://hypernews.cern.ch/HyperNews/CMS/get/JetMET/1622/1.html). 
The L2L3 residual corrections have been removed from slimmedMETs and slimmedMETsNoHF for the moment. This has to be updated as soon as the new corrections are available.

MET without HF added

---

common/include/JetHists.h
common/include/TopJetIds.h
common/src/JetHists.cxx
common/src/LuminosityHists.cxx
common/src/TopJetIds.cxx
core/include/TopJet.h

For the HepTopTagV2 TopJetId I used the cuts for the 40% efficiency WP given in the talk about top tagging in this B2G meeting: https://indico.cern.ch/event/393337/#preview:1078843. The cuts have to be updated when there are new recommendations.

changed some histograms inTopJetHists, added TopJetIds: HepTopTagV2, Type2TopJet, Tau2/Tau1

---

common/include/MuonIds.h
common/src/MuonIds.cxx

* added routines for some muon IDs (loose and medium)
* https://twiki.cern.ch/twiki/bin/view/CMS/SWGuideMuonIdRun2

added selectors for muon IDs

---

common/include/ElectronIds.h
common/src/ElectronIds.cxx

* added electron-ID selectors for non-triggering MVA ID [Spring15-25ns working points]
* https://twiki.cern.ch/twiki/bin/viewauth/CMS/MultivariateElectronIdentificationRun2

added selectors for electron IDs [MVA-notrig; Spring15-25ns;]

---

common/src/ElectronIds.cxx
common/src/PrintingModules.cxx
core/include/Electron.h
core/plugins/NtupleWriterLeptons.cxx
core/plugins/PATElectronUserData.cc
core/python/ntuplewriter.py

* updates for electron reco in UHH2 for latest recipe in CMSSW_7_4_9
* fixed electron ID references in core/python/ntuplewriter.py
* removed PHYS14 tags from Electron class
* added setter and getter for effective-area variable in Electron class
* fixed isolation variable used in Electron CutBased-IDs (effective-area correction, instead of delta-beta correction), following the procedure used by the EGamma POG, see
* https://github.com/ikrav/cmssw/blob/egm_id_747_v2/RecoEgamma/ElectronIdentification/python/Identification/cutBasedElectronID_tools.py#L262
* https://github.com/ikrav/cmssw/blob/egm_id_747_v2/RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleEffAreaPFIsoCut.cc

updates for electron IDs

---

core/include/Electron.h
core/include/Muon.h
core/plugins/NtupleWriterLeptons.cxx
core/plugins/PATMuonUserData.cc

* [commit_#1] added reconstruction-related variables to the Muon class in order to be able to reproduce/validate the Loose, Medium and TIght muon IDs (similarly to what is done for the electron class) [https://twiki.cern.ch/twiki/bin/view/CMS/SWGuideMuonIdRun2]
* [commit_#2] enabled tags in Muon and Electron classes to save 2dcut-related variables
* motivation: in the analysis, the 2d-cut variables (minimum delta-R and pTrel) are calculated with respect to a "looser" collection of jets. when the jets are cleaned (with the final pt-eta cuts), the jet collection changes and there is no way to re-obtain the floats used in the 2d-cut evaluation. this change gives the possibility to save these variables in muon/electron objects on-the-fly at the analysis level (and does not really change the …

updates for Muon class in core/

---

common/include/ElectronIds.h
common/src/ElectronIds.cxx

* updated thresholds for electron cut-based ID
* https://hypernews.cern.ch/HyperNews/CMS/get/egamma/1623.html
* https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2
* restructured the implementation of the ElectronID selectors in common/\*/ElectronIds.\*
* these updates are backward-compatible (only the underlying implementation has changed)
* the idea is to simplify the hard-coding of thresholds and make the implementation (as much as possible) not error-prone
* the new implementation complies with the "table" structure that the Egamma twikis use for the ID working points
* this allows to update/add ID recipes more easily, just copying the twiki table all at once in one place (instead of hard-coding thresholds 1-by-1 in different places)
* also, the implementation …

updates for common/ElectronIds [UHH2:RunII_50ns]

---

core/include/Jet.h
core/plugins/NtupleWriterJets.cxx

* added "hadronFlavor" member to Jet class in core/
* pat::Jet variable needed to comply with the latest b-tag POG recommendations
* https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideBTagMCTools
@imarches

added hadronFlavor to Jet class

---

common/include/TauIds.h
common/src/TauIds.cxx
core/include/Tau.h
core/plugins/NtupleWriterLeptons.cxx

The tau object was cleaned up in the ntuplewriter. Old discriminaters have been killed, also I filled new discriminators which are recommended for Run II.
Moreover, some tauids have been added. Also, the againstElectronTightMVA5 discriminator was changed to medium as it is recommended from the tau POG.

cleaning the tau object

---

core/include/TopJet.h
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriterJets.cxx
core/plugins/NtupleWriterJets.h
core/python/ntuplewriter.py

* added a 'soft-drop mass' member to the TopJet class (similarly to what is done for the pruned mass)
* currently storing the uncorrected softdrop mass from the miniAOD collection (only for the slimmedJetsAK8 collection)

added soft-drop mass to TopJet

---

core/python/ntuplewriter.py

I noticed that the MET corrections in our ntuplewriter.py script were not running for MC in the latest CMSSW_7_4_X release. According to https://twiki.cern.ch/twiki/bin/view/CMS/MissingETUncertaintyPrescription#Instructions_for_7_4_X_X_12 they are not needed anymore. I removed the snippet from corMETFromMiniAOD.py completely because the corrections are supposed to be fully included in the default configuration. 
Could anyone else have a look into the twiki pages an confirm that this is correct?

remove MET corrections

---

core/include/Electron.h
core/include/Jet.h
core/include/Muon.h
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriterJets.cxx
core/plugins/NtupleWriterJets.h
core/plugins/NtupleWriterLeptons.cxx
core/plugins/NtupleWriterLeptons.h
core/python/ntuplewriter.py

* implemented the storage of 'candidate-keys' in leptons and (AK4) jets, in order to be able to apply jet-lepton cleaning by ref-matching at the analysis level
* added list of source candidates in 'Muon' and 'Electron' collections
* added list of daughter keys in AK4 Jet collections (only those linked to muons or electrons are kept, to save disk space); also to save disk space, the keys are not kept in TopJet collections and their subjets (the implementation is actually there for 'NtupleWriterTopJets' as well, but it is switched off at the moment)
* this new feature can be switched on/off with the NtupleWriter option "save_lepton_keys" (see ntuplewriter.py)
* based on some small local tests, the output size should increase only by a few percent (between 1% and 3%, depending on the …

jet-lepton keys in ntuple format

---

core/include/Electron.h
core/plugins/NtupleWriterLeptons.cxx

* added 4 variables to the Electron class
* these vars are used in the 'triggering-preselection', which is part of the recipe to use the electron triggering-MVA ID
* see https://twiki.cern.ch/twiki/bin/view/CMS/MultivariateElectronIdentificationRun2#Triggering_electron_MVA_details under "Triggering electron MVA recommended preselection"

updated Electron class (vars for triggering-preselection)

---

common/include/ReconstructionHypothesis.h

* return top*_jets() vectors by reference, as opposed to by value

fix for ReconstructionHypothesis in common/

---

core/include/Electron.h
core/include/Jet.h
core/include/Muon.h
core/include/NtupleObjects.h
core/include/SUHH2core_LinkDef.h
core/include/source_candidate.h
core/plugins/NtupleWriterLeptons.cxx
core/python/ntuplewriter.py
core/src/classes.h
core/src/classes_def.xml

* fix to correctly handle the ROOT dictionary of the 'source_candidate' class
* removed struct used in Muon and Electron, added it as standalone class with all standard calls for handling dictionaries (e.g. see core/src/classes*)
* previous dictionary handling (currently in UHH2:RunII_25ns_v2) leads to problems when analyzing ntuples, in some cases: not possible to read ntuples produced with crab (2 and 3), things seem ok using grid-control (not sure why).
* some fixes in Muon, Electron and Jet (pass vector objects by const-ref)

fix for source_candidate class dictionary in core/

---

core/include/Electron.h
core/include/Jet.h
core/include/Muon.h
core/include/NtupleObjects.h
core/include/SUHH2core_LinkDef.h
core/include/source_candidate.h
core/plugins/NtupleWriterLeptons.cxx
core/python/ntuplewriter.py
core/src/classes.h
core/src/classes_def.xml

* back-port of dictionary fix added to master #271
* added one more fix from Heiner  to make this update backward-compatible, i.e. to be able to read ntuples produced with grid-control up to now
* ntuples produced in UHH2:RunII_25ns_v2 with crab* *before this update* remain invalid
* with this update, people can now also use crab* to contribute to the RunII_25ns_v2 ntuple production

cherry-picked 8028d0c + compatibility fix by HT for reading RunII_25ns_v2 ntuples

---

common/include/MCWeight.h
common/src/MCWeight.cxx

I've restructured PUWeight a bit and added systematic uncertainties in the same fashion as for the BTagWeight class.
For MC, pileup_directory_50ns and pileup_directory_25ns are supported for backward-compatibility, but the new token should be pileup_directory.
Please review the code and let me know if it's fine. If so, I'll also create the PRs for the master and 76X branches.

systematic uncertainties in PUWeight

---

common/include/CleaningModules.h
common/include/JetCorrections.h
common/src/CleaningModules.cxx
common/src/CommonModules.cxx
common/src/JetCorrections.cxx
common/test/TestJetLeptonCleaner.cpp
common/test/TopJetId.cpp
common/test/test_JLCkey.cpp
core/plugins/NtupleWriter.cc
examples/src/ExampleModule.cxx
examples/src/ExampleModule2.cxx
examples/src/ExampleTTbarRec.cxx

* Changed ntuplewriter so that lepton keys will be stored also for TopJets
* Changed  JetLeptonCleaner_by_KEYmatching so that it can also run over TopJets (tested it so that it doesn't break anybody's code)
* Changed JetCleaner and TopJetCleaner classes so that they can run over arbitrary collections
* Classes in UHH2/common are changed accordingly so that the code compiles, however, users might have to change their private analysis code to account for this change. This simply requires adding ctx in the construcutor of the JetCleaner and TopJetCleaner classes

Implement TopJetLepton cleaning and change JetCleaner and TopJetCleaner

---

.gitignore
common/include/JetCorrections.h
common/src/JetCorrections.cxx
common/test/test_JER.cpp
common/test/test_JER.xml
common/test/test_JLCkey.cpp

* no changes in existing modules
* added generalized version of JetResolutionSmearer (for non-default jet collections) in common/\*/JetCorrections.\*
* added an example to test the output of the \*JetResolutionSmearer modules in common/test/test_JER.\*
* updated .gitignore to hide ZprimeSemileptonic/

added GenericJetResolutionSmearer in common/

---

common/include/MCWeight.h
common/src/MCWeight.cxx

This is needed in case btagging for different jet collections is used in the same analysis (e.g. AK4 and AK8). This way one can specify different efficiency files for the different jet collections and correct them separately.

add option to configure the name of the xml parameter for MCBTagScaleFactor

---

common/include/MCWeight.h
common/src/MCWeight.cxx

needed to avoid conflicts when applying btagging SF on more than one jet collection

add possibility to set name postfix for stored btag weights

---

common/include/MCWeight.h

to reduce misunderstandings regarding the issue  "new CSVv2.csv for 76X doesn't work on the 76X branch #403" 
@emanueleusai

change of default value in BTagScaleFactor

---

common/include/ElectronIds.h
common/src/ElectronIds.cxx

* bugfix for ElectronID_HEEP in common/ElectronIds
* absolute value requirement was missing in the "dEtaInSeed" and "dPhiIn" cuts
* code editing (just alignment), no further change intended
* changes transparent to users
* please, if this is ok, cherry-pick to master (does not apply to RunII_25ns_v2)

fixed electronID-HEEP in common/ElectronIds

---

scripts/crab/DasQuery.py

The version of OpenSSL changed. Now it does a server verification. The needed certificate is located in the folder in SSL_CERT_DIR

make autocompletion work in CMSSW_8X

---

common/include/JetCorrections.h
common/include/LuminosityHists.h
common/src/JetCorrections.cxx

- noRes-JERFile for AK8PFCHS jets in order to derive L2Res corrections
- moved operator<(run_lumi, run_lumi) from LuminosityHists class to run_lumi struct

Added noRes JERFile for AK8PFCHS jets, small change to LuminosityHists.h

---

core/src/UniversalJetCluster.cxx

to calculate the area information for both hotvr and xcone makes the ntuplewrite 3-4 times slower! therefore we only calculate the area with reduced max eta of 4. For xcone only subjets have an area and for hotvr the ghost area is set to 0.02 instead of 0.01

make the module faster

---

common/include/JetHists.h

- Adjusted pT-bins in BTag efficiency hists to match the ones in .csv file for Moriond17

Updated pT-bins in BTag efficiency hists

---

core/include/GenTopJet.h
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriter.h
core/python/ntuplewriter.py

By default only CHF is computed, but it can be configured to compute tau123 for ungroomed GenJets.
@irenezoi: You can take this branch of the code, and uncomment the 4 lines of code to activate tauN computation for ungroomed ak8GenJets:
https://github.com/UHH2/UHH2/compare/RunII_80X_v3...ahinzmann:genjets_tau21?expand=1#diff-7e2adb38be6625c1f9dd1596d535e8f5R843
https://github.com/UHH2/UHH2/compare/RunII_80X_v3...ahinzmann:genjets_tau21?expand=1#diff-7e2adb38be6625c1f9dd1596d535e8f5R849

Add CHF and Nsubjettiness to GenTopJets

---

common/include/CommonModules.h
common/src/CommonModules.cxx

- If a JetId is given to CommonModules and it is used to clean the jet collection, the JetCleaner is now applied after applying JEC, JER and MET smearing. 
This only affects people using CommonModules for jet cleaning with kinematic cuts applied. Might change jet and/or MET connected distributions.

Moved JetCleaner in CommonModules after application of JEC, JER & MET-smearing

---

common/Makefile
core/Makefile

This uses the `scram tool tag <TOOL> <TAGNAME>` command to retrieve the locations of LHAPDF and FastJet `include`/`lib` dirs. This way the tool location only needs updating in `$CMSSW_BASE/config/toolbox/$SCRAM_ARCH/tools/selected/<TOOL>.xml`, and the Makefiles won't need updating.
This is necessary for both the move to 94X, and for remote deployments e.g. on gitlab

Use scram to get inc/lib dirs for Makefiles

---

scripts/install.sh
scripts/install_CMSSW8026_withEGReg_UHH.sh

Since they have deleted Thomas' AFS area, we now need to have another FastJet to link against.
We will use one in my AFS for now.
This PR updates the install script (which updates to tool files).
There will be separate PRs for the 80X and 92X branches.
For future, we will get user's to compile their own copy of FastJet to avoid this problem again.

Fix fast jet linking [master]

---

common/Makefile
core/Makefile
scripts/install.sh
scripts/install_CMSSW8026_withEGReg_UHH.sh

Since they have deleted Thomas' AFS area, we now need to have another FastJet to link against.
We will use one in my AFS for now.
This PR updates the install script (which updates to tool files), and backports #784 to ensure no hard-coded paths in Makefiles

Fix fast jet linking [RunII_80X_v3]

---

common/Makefile
core/Makefile
scripts/install.sh
scripts/install_CMSSW8026_withEGReg_UHH.sh

Since they have deleted Thomas' AFS area, we now need to have another FastJet to link against.
We will use one in my AFS for now.
This PR updates the install script (which updates to tool files), and backports #784 to ensure no hard-coded paths in Makefiles

Fix fast jet linking [RunII_92X_v1]

---

core/Makefile

This should fix the compilation failing:
```
creating /nfs/dust/cms/user/karavdia/SFrame_94X_v1/lib/libSUHH2core.so
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/gcc/6.3.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/6.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lHOTVR
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/gcc/6.3.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/6.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lNsubjettiness
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/gcc/6.3.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/6.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lRecursiveTools
collect2: error: ld returned 1 exit status
../Makefile.common:72: recipe for target '/nfs/dust/cms/user/karavdia/SFrame_94X_v1/lib/libSUHH2core.so' failed
make[1]: …
```

Comment out FastJet libs to fix compilation

---

common/include/BTagCalibrationStandalone.h
common/include/PDFWeights.h
common/src/BTagCalibrationStandalone.cc
common/test/test.cxx
core/test/test.cxx

This cleans up some of the compiler warnings that muddy the output making it hard to spot proper errors. Specifically, it addresses:
- `common/include/BTagCalibrationStandalone.h:177:8: warning: 'template<class> class std::auto_ptr' is deprecated` -> converted the pimpl from `auto_ptr` to `unique_ptr`, requires specifying dtor
- The many warnings from `/cvmfs/cms.cern.ch/slc6_amd64_gcc630/external/boost/1.63.0-fmblme/include/boost/test/impl/junit_log_formatter.ipp` - just ignore these with some preprocessor voodoo, since we can't do anything about them
- Variety of warnings from LHAPDF (`warning: unused parameter 'sep'`, `warning: type qualifiers ignored on function return type`), again just ignore these ones
However, there are still some remaining:
- `src/JetCorrections.cxx:1214:155: …

[94X] Cleanup some of the warnings

---

core/python/ntuplewriter.py

`addJetCollection()` is used to add in reguler, ungroomed AK8PFCHS and AK8PFPUPPI jets with lower pT thresholds. However it has no argument to turn off genParton matching, only to turn off `getJetMCFlavour`, so it breaks when running on data. This fixes that so we can store them as before (taken from ntuplewriter.py in 92X branch)

[94X] Fix patJetsAK8PF[CHS|PUPPI] jets in data

---

core/python/ntuplewriter.py

1) Add in PUPPI MET and CHS MET
2) For the latter, the PATMETSlimmer now has extra fields for `chsMET` and `trkMET`. We don't use these so need to remove them. (Aside: we could utilise this new chsMET part and avoid re-doing CHS MET ourselves?) The CMSSW PR: https://github.com/cms-sw/cmssw/pull/20655

[94X] fix MET config

---

core/include/Electron.h
core/python/ntuplewriter.py
scripts/install.sh

This stores electrons with the preliminary VID from EGamma: https://hypernews.cern.ch/HyperNews/CMS/get/egamma/2006.html
At the moment, they are only the cut-based IDs. The appropriate tags have been added to the `Electron` class, replacing the Summer16 ones (since I assume they're not useful at this point?).
Note that I **haven't** update the `ElectronIds.[h|cxx]` files, as I thought just using the tag in an analysis would be easier, and less likely to lead to transcription errors. 
Also updated install script.

[94X] Update Ntuple electrons with new VID

---

scripts/install.sh

This adds checking out of SFrame to the `install.sh` script. This simplifies things for users, and enforces 1 SFrame per 1 UHH2 deployment as good practice. 
It is set up such that wherever the user runs `install.sh` it will put SFrame and CMSSW there (i.e. not nested)
I've also switched to the GitHub source of SFrame (https://github.com/UHH2/SFrame), to allow further developments if necessary, and incase the SVN link one day breaks. Note that the HEAD of the SFrame master branch is the exact same as the `SFrame-04-00-01` tag used before, so there should be 0 difference.
I'll add another PR to backport this to master as well for future.

[94X] Install SFrame in main install.sh script

---

core/Makefile
core/include/UniversalGenJetCluster.h
core/include/UniversalJetCluster.h
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriter.h
core/python/ntuplewriter.py
core/src/UniversalGenJetCluster.cxx
core/src/UniversalJetCluster.cxx
scripts/install.sh

This re-enables HOTVR & XCONE in the ntuplewriter & config. I have re-added back in the Universal(gen)Clusterer files.
To enable all of this, **I have modified the install script to install FastJet for each user**. Note that in the past we all used Thomas' centralised installation on his AFS.
The rational for this change is:
- It stops the same problem in the future of having one centralised fastjet installation that everyone attempts to use, which may get deleted, breaking it for everyone
- User's can now freely play around with fastjet & contribs independently
- It doesn't take long to compile, < 5 minutes.
However I can understand that it may seem like an additional complication. If you don't want a per-user installation I can go back to one centralised installation on AFS that …

[94X] Re-enable HOTVR & XCONE, + user FastJet

---

core/python/ntuplewriter.py

This changes the AK8Puppi jets (& subjets) to use the PUPPI JEC, not the CHS ones. Since this also affects the "normal" AK8PUPPI jets, is it OK for JEC work as well?
(@abenecke pointed out that a change in master & 92X ntuplewriter.py didn't get propagated through.)

[94X] Use Puppi JEC for Puppi jets

---

common/include/ElectronIds.h
common/src/ElectronIds.cxx
core/include/Electron.h
core/plugins/NtupleWriterLeptons.cxx
core/plugins/PATElectronUserData.cc
core/python/ntuplewriter.py
scripts/install.sh

Update electron IDs to store HEEPv7.0, and the latest MVA IDs.
See https://hypernews.cern.ch/HyperNews/CMS/get/egamma/2013.html
**NOTE** This requires doing an extra bit of setup, see changes in `install.sh`. You should also `make clean && make` to ensure all the changes in `uhh::Electron` are picked up properly.
For HEEP, we only store the pass/fail bool.
For MVA IDs, we store both the MVA values and the pass/fail bools.
The changes to the MVA bits are more extensive as now there are 2 MVA IDs, iso & non-iso, so `uhh::Electron` methods have been updated, as have IDs.
Since the wp80 and wp90 are now not just simple cut values but a formula, I haven't included them in the `ElectronIds.cxx`.
If they ever change, we can redo the calculation using the stored MVA values.
The loose working …

[94X] Update HEEP & MVA Electron IDs

---

scripts/install.sh

Not critical, only meant `scram tool info fastjet-contrib` and `scram tool info fastjet-contrib-archive` wouldn't give a version number

[94X] Fix typo in bash variable name

---

core/plugins/NtupleWriter.cc
core/plugins/NtupleWriterJets.cxx
core/plugins/NtupleWriterJets.h
core/python/ntuplewriter.py

This re-enables the HepTopTagger with only CHS, as per @gkasieczka 's wishes.
The top tagging info is stored in `TopJet::tag` fields of Top candidate jets. To be able to use our standard `add_fatjets_subjets()` , and `TopJets` pattern in the NtupleWriter, I have also enabled CA15 with & without SoftDrop, and also with pruning.  (I have not brought back CA15GenJets as not needed?) 
I also added an extra arg to `add_fatjets_subjets()` to make storing of top tagging info more explicit. Similarly, to make the NtupleWriter a little nicer I have added an extra field to the `PSet`, `toptagging_source`. Before, the source was hardcoded into the depths of the Ntuplewriter.
One should note that the following info is now stored in `patJetsHepTopTagCHSPacked_daughters` branch:
- the jet pt/eta/phi is …

[94X] Bring back the CHS HepTopTagger (& CA15 jets)

---

common/include/MuonIds.h
common/src/MuonIds.cxx
common/src/PrintingModules.cxx
common/test/TestJetLeptonCleaner.cpp
common/test/test_JLCkey.cpp
core/include/Muon.h
core/plugins/NtupleWriterLeptons.cxx
core/python/ntuplewriter.py
examples/src/ExampleModule2.cxx
examples/src/ExampleTTbarRec.cxx

- Enabled muon variables that were still missing
- Now we store all pre-computed IDs and isolations provided by MUO as bits.
- Changed to a more flexible way to access muon ID, isolation. Note that this requires most analyses to tweak their code a bit
- Now we store additional information about the muon type (primary, punchthrough, from quark decays, ...)

Refreshed muons to store additional information

---

core/plugins/HOTVRProducer.cc
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriter.h
core/plugins/XConeProducer.cc
core/python/ntuplewriter.py

This moves the HOTVR & XCone clusterings to their own EDProducers.
The NTupleWriter has been updated to allow storing any number of HOTVR & XCone outputs.
NTuples now have HOTVR run over both pfCandidates and Puppi particles, along with XCone run over pfCandidates as before.
Each producer makes 2 jet collections
- the subjets (`pat::JetCollection`), with instance label `SubJets`
- the main jets (`pat::JetCollection`) with links to the subjets
The NTupleWriter then reads both of these in & converts them to TopJets.
The EDProducers have no clustering parameters options - I just copied & pasted the code from `UniversalJetCluster` class.
I did however add in a rejection of input particles with pt==0, since Puppi can produce such particles which screws up the clustering.

[94X] Move HOTVR & XCone to separate producers; add in HOTVR w/Puppi

---

core/python/ntuplewriter.py

Tip from @ahinzmann : turns out the packedPfCandidates already have puppiWeights stored, so no need to recalculate them.
Puppi module goes from ~0.4s/event to ~0.02s/event ! 🚀 
(This also sped up `hotvrPuppi`, ~1.17s/evt -> ~0.6s/evt ... not sure why but yay)

[94X] Make Puppi use existing weights in PFCandidates to speed up

---

core/include/TopJet.h
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriterJets.cxx
core/plugins/NtupleWriterJets.h
core/python/ntuplewriter.py

This adds 2 more sets of variables to TopJet (& necessary producers in ntuplewriter.py)
It also now makes the Nsubjettiness, ECFs, pruned mass, and softdrop mass sources all optional.
If the relevant sources are not specified, it will use a default value (see `getPatJetUserFloat()`).
New variables:
- **tau_4**, both groomed & ungroomed versions. All topjet collections should now have a tau_4 stored. This as requested by Paolo & Andrea for their analysis.
- Energy Correlation Functions (ECFs) for beta = 1 and beta = 2, for both N=2 and N=3, which are also now stored in MiniAOD, as requested by @ahinzmann . These will probably be used in lieu of tau21 etc in the future, so might as well add them now. Like Nsubjettiness, I have also added in the producers for our reclustered …

[94X] Add tau_4 & energy correlation function variables to TopJet; make some substructure vars optional

---

core/include/MET.h
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriter.h
core/python/ntuplewriter.py

This retires our slMETsCHS collection, in favour of storing the CHS "correction" like as is done in MiniAOD.
The CHS MET is now accessible from `slimmedMETs`, using the `corrPx_CHS()` and `corrPy_CHS()` methods.
The use of "corr" is in keeping with the names from pat::MET: https://github.com/cms-sw/cmssw/blob/CMSSW_9_4_1/DataFormats/PatCandidates/interface/MET.h#L151-L168
Although it should be pointed out that the MET itself **doesn't** have any Type-1 corrections.
@karavdin  / anyone that uses any of these MET corrections: is storing px and py useful? Or is storing pt/phi better? Or the whole LorentzVector?
Unfortunately this saves very little processing time, the previous modules were very efficient:
```
TimeReport   0.000789     0.000789     0.000789  pfMet
TimeReport   0.000019 …
```

[94X] Remove our CHS MET producer, store the official one from MiniAOD

---

core/python/ntuplewriter.py

Remove the CA15 pruned mass (for HepTopTagger collection). I don't think it will be used (we already store the mass of the groomed fat jet the top tagger produces), and it is remarkably slow for one variable (~0.15s / event).
I've left how it could be done in there in comments, incase future someone wants to do it.

[94X] Remove CA15 pruned mass & producers

---

core/include/Muon.h
core/plugins/NtupleWriterLeptons.cxx

MuonPOG recommended for highPT muons getting momentum from the muon track determined by the TuneP algorithm. This stores its pt/eta/phi, plus it's track type. I don't know if it will be used in 2017, but would guess so.
I tried on 500 SingleMu events, and the new pt/eta/phi looks almost identical to the main pt/eta/phi though.

[94X] Store Muon tunePBestTrack pt/eta/phi & track type

---

core/include/Jet.h
core/plugins/NtupleWriterJets.cxx
core/plugins/NtupleWriterJets.h
core/python/ntuplewriter.py
scripts/install.sh

This adds in the production & storage of PUPPI multiplicities for slimmedJetsPuppi, patJetsAK8PFPUPPI, and slimmedJetsAK8. 
The production is done by PATPuppiJetSpecificProducer EDProducers, which have to be added in manually (see `install.sh`). In future, they will be in CMSSW 94X.
We then have to use `updateJetCollection` to update the pat::Jet collections, hence the new collection names.
The reading & storing is a bit of a bodge. Each jet collection has the values stored in a `userFloat` but the name of the map is different for each jet collection.
Really we should get the user to pass in the name of the producer, but at the moment the producer name is auto-generated from the jet collection name, so it can be inferred.
But not sure I can figure out how to do it easily...

[94X] Add PUPPI multiplicities to Jets & TopJets

---

core/plugins/NtupleWriterJets.cxx
core/python/ntuplewriter.py

The important changes here:
- remove L1FastJet level from PUPPI JEC (I know we correct afterwards, but makes debugging comparisons easier)
- the AK8 CHS collection now stores the **ungroomed** pt/eta/phi etc. To recover the groomed 4-vector, one should add the 4-vecs of the subjets. In order to map the groomed subjets to the ungroomed jet, I used a `JetSubstructurePacker` which basically does the same deltaR matching we do inside NTupleWriter for matching jets. Note that I also had to turn off the feature that passing "*CHS" to subjet_source stored the corresponding CHS values from the userFloats - guessing it's a feature that won't be used, since we recluster ourselves
I also took the opportunity to add some comments and rearrange things a bit to make life easier in future. It also …

[94X] Move to ungroomed AK8CHS TopJet vars + cleanup

---

core/python/ntuplewriter.py

Also add groomed NJettiness to slimmedJetsAK8 since it doesn't have it.
I've left in the relevant AK8Puppi bits for future, to avoid having to re-invent everything.
This saves approximately 0.1s / event (with average event time ~ 4.4s for MC), and reduces a 100 event Ntuple by ~0.1 MB. Not really massive, but it does add up.

Remove patJetsAk8PuppiJetsSoftDropPacked_daughters

---

core/include/GenTopJet.h
core/include/JetBTagInfo.h
core/plugins/CandIsolatorFromDepositsMINIISO.h
core/plugins/HOTVRProducer.cc
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriter.h
core/plugins/NtupleWriterJets.cxx
core/plugins/NtupleWriterLeptons.cxx
core/plugins/PATElectronUserData.cc
core/plugins/PATMuonUserData.cc
core/plugins/PFCandIsolatorFromDepositsMINIISO.h
core/plugins/XConeProducer.cc
core/plugins/convertPackedCandToPFCand.cc
core/python/compareTrees.py
core/python/ntuplewriter.py
scripts/install.sh

This allows the ntuplewriter to run with multiple threads, significantly speeding up runtime. In local tests running over 500 MC events, I went from ~4s/evt (1 thread) to ~0.9s/evt (4 threads) and ~0.5s/evt (8 threads). I haven't checked memory usage yet though.
To run `cmsRun` in multithreaded mode, do e.g. `cmsRun -n 4 ntuplewriter.py` where 4 is the number of threads.
You can pick any number, but it shouldn't be more than the number of cores available, and as you use more you get diminishing returns.
**NB** To use multithreading, we now have to use the CMS versions of fastjet and fastjet-contrib, which have thread-safe additions. If you want to run multithreads, you will have to re-install them, see `install.sh`. (The easiest way is to delete the contents of your `fastjet-install` dir, …

[94X] Ntuplewriter with multithreading

---

scripts/install.sh

The fastjet changes from 3.1.0 to 3.2.1 speed up HOTVR significantly.
The contrib changes from 1.026 to 1.032 speed up the ECFs significantly.
NB this should probably be merged **after** #852 to avoid messing up install instructions
To ensure thread-safety, our versions of fastjet & fastjet-contrib has the thread-safety commits that were applied to fastjet 3.1.0 and fastjet-contrib 1.026 from the cms-externals repos.
With multithreading, can get down to < 1s/event.
e.g. 100 TTbar MC, comparing the individual & combined changes
**with 3.2.1 + 1.032 (update both, this PR)**
```
TimeReport   0.016263     0.016263     0.016263  ECFNbeta1Ak8SoftDropCHS <<< !
TimeReport   0.015910     0.015910     0.015910  ECFNbeta2Ak8SoftDropCHS <<< !
TimeReport   0.142428     0.142428     0.142428 …
```

[94X] Move to fastjet 3.2.1 and fastjet-contrib 1.032

---

core/python/ntuplewriter.py

Wasn't storing them before in MC, now does.
Don't know how it worked before in 80X, Twiki instructions haven't changed...?

[94X] Fix input for MET filters in MC

---

common/src/CommonModules.cxx

One MET filter is now not recommended for MC, and another has been added: https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2#Moriond_2018

[94X] Update 2017 ReReco MET filters

---

common/include/JetCorrections.h
common/src/JetCorrections.cxx
core/plugins/NtupleWriter.cc

fix bug to store CHS MET x and y components and not y for both.
correct_met for CHS MET and slimmedMETs are decoupled now. To use it for CHS MET user should call correct_met(event, true). This will set MET to TypeI corrected CHS MET. User also should set L1RC corrector to work with CHS MET. 
The standard call  correct_met(event) will use input collection specified by user (as before, so no change visible for most of users).
Also some cleaning is done to remove not necessary any more flags, etc

[94X]  fix bug to store CHS MET x and y components and add correct_MET for CHS MET

---

common/src/EventHists.cxx
examples/config/MakePileupHistMC.xml
examples/src/MakePileupHistMC.cc

Add in simple analysis to dump pileup info. Also updated binning to match that in the data ROOT file.

[94X] Update EventHists & add MC pileup hist maker analysis

---

core/include/Event.h
core/src/Event.cxx

This is a hack specifically for MC that stored the HLT twice, so it doesn't throw, and only outputs a warning the first event.
For real data we still throw an exception since it is stored correctly.

[94X] Don't throw exception if 2nd occurrence of trigger found in MC

---

core/src/AnalysisModuleRunner.cxx

In new Fall17 PSweights samples (e.g. the ttbar ones) the nominal event weight is **not** the product of all weights in the GenInfo, but only the first entry. (if you multiply them all you get 10^34)
This fixes it so that the `event.weight` is only the first entry.
Was there a prior reason to use the product? Should that still be an option?
Ref links (with varying ages, none seem to be The Definite Uptodate Answer):
https://twiki.cern.ch/twiki/bin/viewauth/CMS/LHEReaderCMSSW
https://twiki.cern.ch/twiki/bin/view/CMS/ScaleAndPDFUncertaintiesFromEventWeights
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideDataFormatGeneratorInterface

[94X] Fix bug using product of all weights

---

common/include/JetCorrections.h
common/src/JetCorrections.cxx
common/test/test_JER.cpp

- Update collection names in the `JetCorrector` to match collection names in ntuples
- Remove unused vars (esp. MET ones in GenericJetResolutionSmearer). No physics changes, but stops compiler warnings which can hide other things

[94X] Tidy up JetCorrections & warnings

---

scripts/install.sh

Remove more old EGamma TMVA XML files from 2011 (I guess they're not used?).
Also prune their `.git`. This reduced it from 43MB to 32 MB.
Altogether saves ~ 7MB from CRAB tarball.

More cleaning up egamma files & prune their .git

---

common/src/TTbarGen.cxx

New attempt without re-indentation: Added workaround in TTbarGen for the rare issue that errors occur due to tops having no b/W daughters. Now, b/W with top mothers are looked for if the initial daughter search fails. The fact, that it must be W+ from top and W- from anti-top, is taken into account. Same for the bottoms. Should probably be in the master as well. Runtime errors are de-commented again.

More robust b/W daughter identification in TTbarGen

---

common/src/JetIds.cxx

updated the tight IDs according to https://twiki.cern.ch/twiki/bin/viewauth/CMS/JetID13TeVRun2017

Run ii 94 x v1

---

common/include/JetIds.h
common/src/CommonModules.cxx
common/src/JetIds.cxx
common/test/test_JER.cpp
common/test/test_JLCkey.cpp

This removes the loose jet ID from the code as no longer recommended/supported, and replaces any occurrences with the Tight ID. Most importantly, this happens in `CommonModules`.
Also updated comments

Remove loose JetID

---

core/python/ntuplewriter.py

In 0f83af71cadabd93c56ef8af55a6066b2793f06b the `doAllGenParticlesPythia8` config param was added to NtupleWriter but not the `ntuplewriter.py` config. The config will fail to run; this fixes it.
This also needs to go into 80X_v4 and master branches.

Add doAllGenParticlesPythia8 to ntuplewriter py config [80X_v3]

---

core/plugins/HOTVRProducer.cc
core/plugins/XConeProducer.cc

This allows them to be used with CHS input as well as PUPPI, PF.
(More technically: previously we only cared about `pat::PackedCandidate` inputs as that was the class for `packedPFCandidates` and `puppi`. But `chs` is produced by a `CandPtrSelector` (https://github.com/cms-sw/cmssw/blob/CMSSW_9_4_1/CommonTools/CandAlgos/plugins/CandPtrSelector.cc) as a `reco::Candidate` collection. Since `PackedCandidate` inherit from this, we'll just move to using `reco::Candidate` instead with no loss of information because we only care about px/py/px/e.)

Make HOTVR/XCONE producers look for reco::Candidate input

---

core/include/GenTopJet.h
core/plugins/HOTVRProducer.cc
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriter.h
core/plugins/XConeProducer.cc
core/python/ntuplewriter.py
core/src/UniversalGenJetCluster.cxx

Updates for HOTVR/XCone:
**Physics changes**:
- Ntuple now has XCone & HOTVR with both CHS & PUPPI, dropping the pfCandidates ones (i.e. what we used to have)
- Move to `PseudoXConePlugin` instead of normal `XConePlugin` for speed gains (both reco & gen level). This saves us ~0.3s/evt/producer, so about 0.6s/evt overall. For reco XConeProducer this is configured by a bool to allow easy testing/changing. For gen level its hard-coded.
- Both producers now filter out input particles with pT= 0.
- Gen level XCone & HOTVR now use genParticles **without neutrinos** - previously had included them. (NB this doesn't affect runtime)
**Code changes**:
- Move clusterers  into own producers and out of UnivesalClusterer
- NtupleWriter can now store any number of XCone/HOTVR collections (reco only)
- …

[80Xv5] Update XCone/HOTVR

---

scripts/crab/DasQuery.py
scripts/crab/test_DasQuery.py

DasQuery returns duplicate dataset entries due to how das_client works. This removes duplicate entries.
Also updated the tests accordingly.
Details in https://github.com/dmwm/DAS/issues/4287#issuecomment-390278822

[80Xv5] Fix issue with duplicate datasets from DasQuery, update tests

---

core/plugins/XConeProducer.cc

XCone crashes if there are too few input particles. Before we checked the size of the particle collection. With PUPPI, we have to check the number of particles with a non-zero puppy weight. This is now changed in the XConeProducer

Checking size of input particles

---

core/plugins/XConeProducer.cc

For each xcone fat jet, check # constituents. If enough, do subjet clustering, otherwise store nothing.
Do this independently for jet 1 & 2, so event is not entirely wasted.
Before, we didn't throw properly when too few constituents in the fat jets, so we never noticed this problem.

[80Xv5] Fix XCone subjets

---

core/plugins/XConeProducer.cc
core/python/ntuplewriter.py

Now you can define the XCone setup (for RECO jets) in the Ntuplewriter.py.
One can set number of jets, cone radius and beta as well as number, radius and beta for subjets. 
If number of subjets are set to 0, no clustering of subjet is performed and empty subjet collections are added to the fatjets. The requirement of sufficient particles is now related to the number of required jets and subjets. 
I also removed a line from the HOTVR in the ntuplewriter where a bool was set which was not used.
I tested this with chs and puppi in 1000 events for both SingleElectron and ttbar.

More generic XConeProducer

---

core/plugins/HOTVRProducer.cc
core/plugins/NtupleWriter.cc
core/plugins/XConeProducer.cc
core/python/ntuplewriter.py
core/src/UniversalGenJetCluster.cxx

Covers:
- Move to CHS & PUPPI for both XCone/HOTVR
- Allow user to choose PseudoXcone or normal (default = pseudo)
- Allow user to configure XCone plugin settings
- Gen level XCone/HOTVR now doesn't include neutrinos
- Properly handle cases where too few particles in XCone
Also includes equivalent fixes for #935 , #936

[94X] Forward-port of HOTVR/XCone changes from 80Xv5

---

core/src/UniversalGenJetCluster.cxx

The closing `)` was in the wrong place.
NB this has some physics consequences - it means that sometimes the highest pT e/mu gets ignored, and another one found, so that the "leptonic" jet is incorrectly identified and thus # subjets is wrong.

[80Xv5] Fix typo where -ve ele/mu not considered in GenXCone23

---

core/plugins/HOTVRProducer.cc
core/plugins/XConeProducer.cc

Previously only stored first set of subjets for all fat jets in the event, rendering the 2nd -> end fatjets useless in terms of subjet info.

[80Xv5] Fix subjet linking for HOTVR/XCone producers

---

scripts/crab/crab_template.py

Otherwise it gives ext1 and ext2 datasets with same request name
same as #942 but for 94Xv2

[94Xv2] Better ext in crab requestName

---

scripts/install.sh

This is due to (I think) a timing issue since we checkout from git? The program itself isn't actually missing. This fixes it and allows compilation to carry on as normal (with a very slight time penalty)
https://stackoverflow.com/questions/33278928/how-to-overcome-aclocal-1-15-is-missing-on-your-system-warning-when-compilin

[master] Add autoreconf to avoid aclocal error

---

common/include/JetCorrections.h
common/src/JetCorrections.cxx

only statistical uncertainties included. 
Used only for testing.
Included also JEC for AK8PFPuppi and AK4PFchs (V10, V11, V12)

first version of JER SFs for 2017

---

common/src/MCWeight.cxx

Proper version of #978 without all whitespace changes.
Set handles properly incase of bad number of interactions.

[94X] Fix PU systematic weights in bad events

---

core/src/Event.cxx

This commit is to raise the same error: assertion error ->runtime error. It's easier to catch.
In the past runtime error was raised if the trigger Name was not present since the first event of the sample. Whereas assertion occurs if the trigger name was not present in the middle of the sample. 
Now both cases raise a runtime error.

bug fixed in trigger pass

---

scripts/install.sh

The fastjet-contrib SVN is no longer reachable by anonymous users (i.e us). I have copied the HOTVR contents to a github repo: https://github.com/UHH2/HOTVRContrib, and this updates the install script to now use that repo as the source of HOTVR.
(cf https://discourse.phabricator-community.org/t/public-svn-fails/1917)
Related, I have also turned on the option that if a command fails, the whole install script fails. e.g. the failure to checkout from svn was not visible, only when do `scram build` when it couldn't find `HOTVR.hh`
Unrelated, I have also taken the opportunity to disable the use of auto-ptr in fastjet. As far as I can tell, using auto-ptr was a backwards-compatible option that we don't actually need. This removes all the warnings that come when compiling.
Also added in the …

[master] Update install script for HOTVR + other niceties

---

core/include/Electron.h
core/python/ntuplewriter.py

Remove "preliminary" V1 electron IDs, moved to newer V2 IDs.
Note that in the V2 MVA ID there's a new Hzz working point which I **haven't** included as I assumed it isn't needed. But we can add it in if there's a use case
Refs:
https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2#Recipe%20for%20regular%20users,%20format
https://twiki.cern.ch/twiki/bin/view/CMS/MultivariateElectronIdentificationRun2#(Recommended)%20MVA%20Recipe%20V2%20for

[94X_v3] Update to electron V2 cut & MVA IDs from V1

---

core/python/ntuplewriter.py
examples/config/ExampleElectronID.xml
examples/src/ExampleModuleElectronID.cxx

Added in simple module to show how to use electron ID tags, also good check to tell if they're actually being filled.
Also spotted that the electron effAreas file was out of date. They don't publicise when they update this, so to avoid future errors, I'm now just directly getting the filename from the egamma module, from the same place they define it. So we should now remain up to date, or at least it'll break if they move it :)

[94X_v3] Add example electron ID module, update electron eff area file

---

scripts/install.sh

These were originally needed when CMSSW didn't support
fastjet >=3.2.1. Now it does, so we don't need these packages.

[102X] Remove unnecessary cms-addpkg

---

scripts/install.sh

I  checked how CMSSW compile fastjet - turns out they add in a series of optimisation flags, that until we now we did not use.
I tried adding recompiling with these, and it is now significantly faster. However, I didn't enable `-ffast-time`, since when running fastjet-contrib checks it fails the Nsubjettiness tests. Reading up on the flag, it seems to take some shortcuts in float-point math, so I'm going to leave it out for safety.
I also updates the list of builtin plugins fastjet compiles to match the CMSSW list (basically just drop PxCone).
I ran over 500 QCD MC events from Fall17 with & without the optimisation flags, and all variables have the exact same distributions, so the maths shouldn't be affected (if it is, it will be in CMSSW as well!).
Here are some timings from those 500 MC …

[102X] Add CMSSW flags to fastjet(-contrib) compilation, including optimisation & more error checking

---

core/python/ntuple_generator.py

As requested by @rkogler , this removes HOTVR with CHS input, as it will no longer be needed since HOTVR w/PUPPI outperforms it.
This also saves us some processing time (#1050 suggests ~ 8%). It also saves a little disk space (~ 500KB reduction in ntuple file size for 500 events)

[102X] Remove HOTVR jets with CHS input

---

core/plugins/GenXConeProducer.cc

Make the warning messages about missing lepton when using with `doLeptonSpecific` into info messages so that by default they do not clutter the screen output. This clutter obscures new/different warnings.
(Might also do this for the `GenXConeTooFewSubjets` messages...)

[102X] Downgrade GenXCone lepton warnings

---

core/include/Event.h
core/python/ntuple_generator.py
core/src/Event.cxx
examples/config/ExampleTrigger.xml
examples/src/ExampleModuleTrigger.cxx

3 trigger-related fixes:
- Fix return type for `Event::trigger_prescale` from `bool` to `int` (was already storing correctly as `int` in the Ntuplewriter, just accessing it was wrong).
- Fix trigger collection name for 2016v2 (dunno why it's different there...)
- Update example trigger module to show `TriggerSelection` usage, trigger prescale lookup, and MET filter check as well. This makes it useful for more general trigger testing (i.e. did we actually store things correctly!)

[102X] Fix trigger prescale access; trigger collection for 2016v2; trigger example

---

core/include/Event.h
core/include/EventHelper.h
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriter.h
core/python/ntuple_generator.py
core/src/Event.cxx
core/src/EventHelper.cxx
examples/src/ExampleModuleTrigger.cxx
scripts/install.sh

This adds in the machinery to store weights to emulate L1 ECAL prefiring in 2016 & 2017. Ref: https://twiki.cern.ch/twiki/bin/viewauth/CMS/L1ECALPrefiringWeightRecipe
**It is currently disabled, since handling the location of the ROOT weights file is not easy/proper!**
This should be enabled only for `2016v2`, `2016v3`, and `2017` eras, and only for MC. (Maybe 2016v3 doesn't need it?)
However, we now always store the prefiring weights branches (main value, along with up & down variations) with a default value of 1, since it makes the `EventHelper` easier. Since these are only 3 floats, it doesn't take up a huge amount of space. But maybe I should only do it for the samples that need it?
Note that this isn't the final recipe: the prescription will become part of CMSSW_10_2_X at some point, …

[102X] Add L1 prefire weights

---

core/python/ntuple_generator.py
scripts/crab/crab_template.py

As requested after #1061 I've added a note about setting up L1 prefiring for CRAB jobs, both in the ntuple generator, and the crab template. I've also updated the inputfiles for crab_template, since we have to manually tell it where the file is since they didn't put it in a `data` dir.
I've also turned off the always-disabled that was on before.

[102X] Add note to setup L1 prefiring for CRAB jobs, update crab_template as well

---

core/python/ntuple_generator.py

This was erroneously uncommented during CRAB testing

[102X] Comment out wrong L1 prefire file location

---

common/include/JetCorrections.h
common/src/JetCorrections.cxx

lots of indentations applied. Sorry about that!
I'd like also to cross-check all the version for JER and JEC present because most of them are not used anymore. Could be useful to think about how to simplify even more the preprocessing directives (maybe for the next iteration).
Once that this is approved, I'd like also to propagate the same changes (SF and new MET) also in 94X_v1 and 94X_v2 branches.

merge of JEC and JER between branch 94X_v2 and 94X_v3

---

scripts/install.sh

This is the largest file in the CRAB tarball, making it perilously close to the upload limit of 100MB:
```
33028538 external/slc6_amd64_gcc630/data/RecoEgamma/ElectronIdentification/data/.git/objects/pack/pack-29a80f55679276cfbf198603acd6889a96414597.pack
```
(size in Bytes)
It has no purpose for analysis. And since they now move to v2 IDs (which is in 94X_v3 branch as it requires 9_4_9+), we shouldn't ever need to pull

[94Xv2] Remove .git from EGamma external files as inflates CRAB tarball

---

scripts/install.sh

This removes the following EGamma ID data files since they contribute unnecessarily to the CRAB tarball and make it too large:
- PHYS14
- Spring15
- Spring16
- Summer16
as seen in #1076 .
Note that the only Electron IDs in this branch used are the Fall17 V2 ones, so should be safe.
CRAB tarball drops dramatically in size, I measured it now as 75MB, down from 108MB.

[94Xv3] Remove old EGamma ID files during installation to slim CRAB tarball

---

core/plugins/NtupleWriter.cc
core/python/ntuple_generator.py
scripts/crab/crab_template.py
scripts/install.sh

With 10_2_10, they integrated the L1 ECAL prefiring module properly: https://github.com/cms-sw/cmssw/releases/tag/CMSSW_10_2_10.
This PR now changes the install script to use 10_2_10, and removes the L1 prefire merge-topic. We also now use this new module, which thankfully removes all the faff with finding the weights ROOT file. The user no longer needs to specify anything in their CRAB config, nor worry about changing paths in their `ntuple_generator.py`.
Note that the label capitalisation changed, hence the changes in `NtupleWriter.cc`
(I'm also tempted to just import the cff file and save a few lines of code? Although more explicit here what's going on (e.g. systematics size))

[102X] Move to CMSSW_10_2_10 + properly do L1 prefiring

---

core/include/Electron.h
core/plugins/NtupleWriterLeptons.cxx
core/plugins/PATElectronUserData.cc
core/python/ntuple_generator.py
examples/src/ExampleModuleElectronID.cxx

Adds back in the electron IDs from 80X branch:
- heepElectronID_HEEPV60
- cutBasedElectronID_Summer16_80X_V1_veto
- cutBasedElectronID_Summer16_80X_V1_loose
- cutBasedElectronID_Summer16_80X_V1_medium
- cutBasedElectronID_Summer16_80X_V1_tight
- cutBasedElectronHLTPreselection_Summer16_V1
(see https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2#Working_points_for_2016_data_for)
+ the MVA values for GeneralPurpose and HZZ, and the correct eff area file.
I also updated the ExampleElectronID module with the new IDs, and also added in plots for the MVA values to check they're OK.
There's also some whitespace tidying up.
Some notes/questions:
- HEEPv7 is the one now recommended for 2016 and 2017/8, but it seems we had HEEPv6 in the 80X branch. I've added it back in for …

[102X] Add 2016 electron IDs back in

---

core/include/Event.h
core/include/EventHelper.h
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriter.h
core/python/ntuple_generator.py
core/src/Event.cxx
core/src/EventHelper.cxx

This saves the `year` parameter used in the ntuple_generator to the Ntuple tree itself.
Analysis modules can then dynamically change their behaviour depending on this parameter, or the user can choose how to utilise it.
A string was chosen instead of an int, because the latter relies on some immutable mapping (or rather, never changing the order of existing values). This way, the user can immediately inspect and has more control over how to react. 1 string is also a very small overhead.
I guess the only question is: is "year" a good variable name? Or should it be something like "era"? (Can change the arg name in `generate_process()` as well)

[102X] Save year arg in `generate_process()` to Event class

---

core/python/ntuple_generator.py

The `rParam` in `addJetCollection()` is only used for jet-* matching (e.g. jet-genjet). It does not control the size of the jet cone, which must be determined in whatever FastjetJetProducer you feed in as `jetSource`. So now we ask that FastjetJetProducer directly for it's `rParam`, so that there is only one place to set your desired jet cone size (in the original FastjetJetProducer doing the jet clustering).

[102X] Automatise rParams for patJetsAK8PFCHS/PUPPI

---

core/python/ntuple_generator.py

Same as in 94X_v3. Note that the necessary updates went into 10_2_7 release, so no extra recipes steps required since we are now on 10_2_10 (see #1091 )
References: 
https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETUncertaintyPrescription?rev=89#Instructions_for_9_4_X_X_9_or_10
https://github.com/cms-sw/cmssw/releases/tag/CMSSW_10_2_7

[102X] Store MET with EE noise mitigation only for 2017

---

core/include/MET.h
core/plugins/NtupleWriter.cc

A hodgepodge of MET changes:
- for 2016v2, rawCHS is not stored. The code does run & store something, but no idea where it gets those values from. This variable often shows up in our tests as differing (with massive values sometimes), even though nothing has changed. So now I've just it to the usual MET px & py.
- now store sumET in MET
- replaced `MET::mEtSig` (which was actually = MET/sqrt(sumEt)) with `MET::mEtSignificance`, taken from the full covariance matrix. I changed the name (a) to match the `pat::MET` method, and (b) to ensure that any analyses using `mEtSig` are alerted to this change. The old `mEtSig` is still available, since we now store sumEt.
Note that for gen met, the significance matrix isn't stored, and instead requires explicit calculation. Given we don't even store …

[102X] MET fixes: rawCHS for 2016v2, add sumEt, use proper MET significance

---

common/test/test.cxx

This should remove the annoying warning when compiling:
```
In file included from /cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/boost/1.63.0-gnimlf/include/boost/test/included/unit_test.hpp:21:0,
from test/test.cxx:8:
/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/boost/1.63.0-gnimlf/include/boost/test/impl/framework.ipp: In function 'void boost::unit_test::framework::run(boost::unit_test::test_unit_id, bool)':
/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/boost/1.63.0-gnimlf/include/boost/test/impl/framework.ipp:1436:14: warning: this statement may fall through [-Wimplicit-fallthrough=]
seed = static_cast<unsigned>( std::rand() ^ std::time( 0 ) ); // better init using std::rand() ^ ...
~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```

[102X] Ignore -Wimplicit-fallthrough from BOOST unit_test header

---

core/include/Muon.h
core/plugins/NtupleWriterLeptons.cxx
examples/config/ExampleMuonID.xml
examples/src/ExampleModuleMuonID.cxx

Add 2016v2/80X Selectors back in, since those samples to do not use the more fine-grained Selectors that are used in 94X.
Also add in example module that plots which Selectors are filled, and the distributions of TrackTypes and SimTypes. Good for testing & showing how to use `Muon::get_selector()`

[102X] Add 2016v2 Muon Selectors back in, + module to test all Selectors & plot TrackType + SimType

---

core/python/ntuple_generator.py

Checked with Roman & Gregor, there are no plans to carry on HepTopTagger studies. So it's time to retire this collection & all the associated CA15 collections. I've merely commented them out, incase one needs them in future - they were tricky to enable in the first place.
This should save us a good chunk of processing time & some disk space, I hope

[102X] Retire HepTopTagger & CA15

---

core/plugins/BuildFile.xml
core/plugins/GenXConeProducer.cc

To save gen information obtained by looping over gen jet constituents, add links to them for xcone gen jets. "transformation" from PseudoJet to pat::Jet is re-written with adding PseudoJet->reco::GenJet->pat::Jet steps. 
To large extend inspired by [1] 
[1] https://github.com/cms-sw/cmssw/blob/master/RecoJets/JetProducers/plugins/VirtualJetProducer.cc
P.S: parton and hadron flavor information is still not filled for unknown reasons :(

[102X] Save links to  XCONE gen jets constituents

---

core/plugins/NtupleWriterLeptons.cxx

Default for fraction attributed to Bremsstrahlung in miniaod is -1e-30, which makes automated plotting difficult. This sets the minimum to -100 instead, which should be a safe, obvious value, and still show some differentiation power of 0 - 1  vs ==0.
(Aside, I see some electrons with -ve fbrem, does that even make sense? The code to calculate this is: https://github.com/cms-sw/cmssw/blob/CMSSW_10_2_10/RecoEgamma/EgammaElectronAlgos/src/GsfElectronAlgo.cc#L1482 , essentially `fbrem = (inMomentum - outMomentum) / inMomentum`, so -ve values indicate `outMomentum > inMomentum`...)

[102X] Electron::fbrem now stores saner default value

---

core/include/Event.h
core/include/EventHelper.h
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriter.h
core/python/ntuple_generator.py
core/src/Event.cxx
core/src/EventHelper.cxx

Store a bool. `True` if no bad crystals over the threshold.
As per https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2#How_to_run_ecal_BadCalibReducedM it is only run for 2017,8 data
Unsure exactly which list of DetIDs to use as there are 2 in the twiki page, TBC later.

[102X] Add ECAL bad crystal filter bool

---

core/python/ntuple_generator.py

Add these in since they were not in CMSSW at the time. I believe they _should_ be there for 2016v3.
Note that these are run in filter mode, i.e. they reject events, rather than storing a Flag. This is as done in MiniAOD, I believe.
Also some trailing whitespace removal while I'm at it.

[102X] Bad muon & bad charged filters for 2016v2

---

core/include/Jet.h
core/plugins/NtupleWriterJets.cxx
examples/config/ExampleJetTags.xml
examples/src/ExampleModuleJetTags.cxx

Add in `Jet` tags for the loose/medium/tight pileup working points. Also add in example module showing how to use, and histogramming frequency of each ID to test.

[102X] Store pileup working points

---

core/plugins/NtupleWriterJets.cxx
core/python/ntuple_generator.py

Several things happen here:
- We now recluster our own AK8 PUPPI jets with all the melange of substructure and tagging. This replaces our reliance on slimmedJetsAK8, ensuring we have a consistent and flexible collection across all datasets, at the cost of extra runtime. It also means we don't have to worry about daughters really being subjets in some datasets. The new AK8 PUPPI mirrors the already existing AK8 CHS used for TopJets, with the extra deep* stuff
- Sorted out the DeepFlavour/Tagging + PUPPI PATPuppiJetSpecificProducer modules so that we only have one call to `updateJetCollection`, removing the extra jet collections. The trick is to do the PUPPI bit only for the very last `PATJetUpdater` module (since we use the collection name for userFloats) [Aside: the deepFlavour stuff …

[102X] Recluster AK8PUPPI for TopJets ourselves

---

core/include/Jet.h

0 is dangerous as it's a valid discriminant output. -2 should be outside the range of any discriminant, but still makes automated plotting useful

[102X] Set btag discriminant defaults to impossible value

---

core/include/EventHelper.h
core/include/Jet.h
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriter.h
core/plugins/NtupleWriterJets.cxx
core/plugins/NtupleWriterJets.h
core/plugins/XConeProducer.cc
core/python/ntuple_generator.py
core/src/EventHelper.cxx

The feature is enabled by "doPFJetConstituents" flag (=number of jets for which PF candidates should be stored and linked to Jet).  At the moment one flag for all jet collections for simplicity. Might be useful for comparing leading jets between each other.

[102X] add storage of PF candidates for selected number of reconstructed jets

---

core/python/ntuple_generator.py

Doesn't change contents, only the name in the Ntuple output file. This brings it in line with the other jet collections names for consistency.
FYI can't use `EDAlias` here as it's a collection made by a different process

[102X] Rename `slimmedJets` -> `jetsAk4CHS` using dummy selector

---

core/include/Jet.h
core/plugins/NtupleWriterJets.cxx
core/python/ntuple_generator.py

Add missing variable for b-tagging as suggested in [1].
Also fixed DeepDoubleB_probQCD in DeepDoubleBJetTags 
Useful links:
- BTV Summary, Dec.2018
https://indico.cern.ch/event/777545/contributions/3234584/attachments/1766808/2869123/BTV_CMS_Week.pdf
- DeepDoubleBJetTags
https://cmssdt.cern.ch/lxr/source/PhysicsTools/PatAlgos/python/recoLayer0/bTagging_cff.py?%21v=CMSSW_10_2_0
- DeepBoostedJetTags
https://twiki.cern.ch/twiki/bin/view/CMS/DeepAKXTagging
https://cmssdt.cern.ch/lxr/source/RecoBTag/MXNet/plugins/DeepBoostedJetTagsProducer.cc
NB: DeepDoubleX and DeepBoostedJet seems to work only for AK8PUPPI, for CHS are not filled even if added to the "updateJetCollection" list.
[1] https://github.com/UHH2/UHH2/pull/1117#issuecomment-460931570

[102X] Add missing variables for b-tagging

---

core/include/Photon.h
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriterLeptons.cxx
core/plugins/NtupleWriterLeptons.h
core/plugins/PATPhotonUserData.cc
core/python/ntuple_generator.py

Add photons to ntuples in similar fashion as muons and electrons. Photon class is updated to store PhotonID tags for RunII. Isolation variables are copied from slimmedPhotons miniAOD collection.
For updates in immediate future might be useful:
https://cmssdt.cern.ch/lxr/source/DataFormats/PatCandidates/interface/Photon.h?%21v=CMSSW_10_2_0

[102X] add Photons 

---

core/include/Jet.h
core/include/TopJet.h
core/plugins/NtupleWriterJets.cxx
core/plugins/NtupleWriterJets.h
core/python/ntuple_generator.py

Add DeepBoosted info to AK8CHS jets. Also DeepFlavor info is filled for AK4 jets, including AK4 sub-jets of top-jets.

[102X] add DeepBoosted info to AK8CHS jets

---

core/python/ntuple_generator.py

If JECs are generally > 1, then the effective cut on topjets is larger than `topjet_ptmin`. This way we retain jets from ~150 - 170 or so.

[102X] Lower fatjet_ptmin to account for JECs

---

core/include/GenTopJet.h
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriter.h
core/python/ntuple_generator.py

Store ungroomed & groomed gentopjet collections, both now have tau_1,2,3,4. Also add ECFs to GenTopJet class, only store for groomed genjets like for TopJets.
tau_2,3,4 seems to be calculated as 0 for groomed GenTopJet, I don't know why - the setup is the same as for TopJets, and tau_1 is non-zero.
Also tried to simplify sources a bit to avoid too much repetition.

[102X] GenTopJet substructure vars

---

core/plugins/NtupleWriter.cc
core/plugins/NtupleWriter.h
core/plugins/NtupleWriterJets.cxx
core/plugins/NtupleWriterJets.h
core/python/ntuple_generator.py

Upon request, handles to store PF and GEN constituents are changed. Now, in addition to storing constituents for certain number of jets (with flag doPFJetConstituentsNjets), one can also store them for (all) jets above pt threshold (with flag doPFJetConstituentsMinJetPt). If not used, min pt threshold should be set to 0 or negative value to be handled properly.
Each family of jets (AK4 jets, TopJets, HOTVR, XCone, XCone_dijet) has its own set of flags. The same is true for GEN jet families. 
Minor changes: removed genXCone23 and added XCONE_dijet PUPPI jets.

[102X] add more flags for PF/GEN constituents storing

---

core/python/ntuple_generator.py

No use case I'm aware of, and IDs are definitely out of date. Safer to drop.

[102X] Drop taus from NTuples

---

core/include/GenJet.h
core/plugins/NtupleWriter.cc

Add multiplicities to GenJet class, same as those for Jet class. Also done for GenTopJet explicitly from its subjets, like for the energy fractions.
Useful especially for the lepton genjets that require a cut on e.g.  ==1 electron and == 0 muon

[102X] GenJet multiplicities

---

core/plugins/GenXConeProducer.cc
core/plugins/XConeProducer.cc
core/python/ntuple_generator.py

Disable warnings about missing L2L3Residual & L3Absolute JECS, these are issued because there's patJetUpdaters that remove JECs.
Also make the XCone warnings user-switchable, default is off now. This should tidy up the output, but still allow testers to turn them on.

[102X] disable warnings from patJetUpdater and (Gen)XconeProducer

---

core/plugins/NtupleWriter.cc
core/plugins/NtupleWriterLeptons.cxx
core/plugins/NtupleWriterLeptons.h

This is because (a) the method didn't exist in 80X when the dataset was made, (b) the pat::Photon constructor doesn't initialise the puppiIsolation variables, so we just read junk values, hence we get values like 10^26, and that differ between runnings.

[102X] Turn off photon puppi isolation for 2016v2

---

core/python/ntuple_generator.py

Since tests in #1139 look OK, we can now remove the lepton genjets from the default list. You can just uncomment one line to add it back in for special samples.

[102X] Disable lepton genjets by default

---

common/src/BTagCalibrationStandalone.cc

Fixes warning, shouldn't affect usage.
Also testing this to avoid running ntuples:
[onlycompile]

[102X] Replace auto_ptr with make_shared

---

core/include/TopJet.h
core/python/ntuple_generator.py
examples/config/ExampleJetTags.xml
examples/src/ExampleModuleJetTags.cxx

Previously used the CHS-derived values for the Puppi jet collections, now we add in a separate one for Puppi.
Also update example Jet Tag module to plot TopJet tags to check them.
Also change the MVA Higgs discriminator value to something outside its possible range of values [-1, 1].

[102X] Fix higgs tagging variables for AK8 Puppi TopJets

---

core/plugins/NtupleWriter.cc
core/plugins/NtupleWriter.h
core/python/ntuple_generator.py

- Rename `doAllGenParticles` to `doStableGenParticles` as better description, add some comments
- Remove `doAllGenParticlesPythia8` flag
- Remove extra filtering logic when storing all the PackedGenParticles
Since we now have the explicit genjet constituent options, this bit is now only useful if the user wants to store some curated list of final-state particle (i.e. packedGenParticles). All filtering logic should be kept explicitly in the python config. The `genparticles_source` covers prunedGenParticle collections (if the user wishes to store e.g. entire parton shower history).

[102X] Tidy up extra genparticle storage options

---

core/python/ntuple_generator.py

change a way how params from grid-control env are extracted
Now grid-control at least works with files stored locally at DESY
[ciskip]
[ci skip]

[102X] fix issue with grid-control running

---

common/include/ElectronIds.h
common/src/ElectronIds.cxx
common/src/JetIds.cxx
common/test/test_JLCkey.cpp
core/include/Electron.h
core/python/ntuple_generator.py
examples/src/ExampleModule2.cxx
examples/src/ExampleModuleEGammaID.cxx

add MVA 2016 electronID tags; 
remove outdated electron IDs; 
update cut-based without iso, which might be useful for some analyses, e.g with boosted semileptonic top

[102X] electronID fixes

---

core/plugins/NtupleWriter.cc
core/plugins/NtupleWriter.h
core/src/AnalysisModuleRunner.cxx
examples/config/Example.xml
examples/config/ExampleJetConstituents.xml
examples/src/ExampleModuleJetConstituents.cxx

- Fill GenTopJet constituents like for GenJets
- Remove unused bools for genjets, they don't appear to be used anywhere
- Setup PFParticles using `PFParticleCollection` name in XML like for other collections
- Add example module that reconstructs Jets, TopJets, GenJets, GenTopJets from their constituents, and tests & plots relative differences in pt/eta/phi
Interestingly, whilst the relative difference in pT is often small (< 1E-3), the relative difference in eta can be > 1E-2!
e.g. for `jetsAk4CHS` in MC 2017 (relative difference = |x-y| / max(x, y)):

[102X] fill GenTopJet genparticles, add jet constituent example

---

core/include/Jet.h
core/plugins/NtupleWriterJets.cxx

`Jet::JEC_L1factor_raw()` is designed to go from uncorrected -> L1 corrected (at least, that's what it's used for in `correct_MET()`, and how it's set in `correct_jet()`). We store it incorrectly when making ntuples.
This value is overwritten once the user applies their own JECs, so no analyses should be affected. It just makes it all consistent from the start.

[102X] Fix jet L1 correction factor stored in ntuplewriter

---

examples/src/ExampleModuleJetConstituents.cxx

No change in functionality. 
[only compile]

[102X] Remove/void unused vars in methods

---

core/plugins/NtupleWriterJets.cxx
core/python/ntuple_generator.py
examples/src/ExampleModuleJetConstituents.cxx

Was cutting on wrong object's pT for Jets & TopJets since the uhh2 class hadn't been set yet. Doesn't affect XCone or HOTVR, nor GenJets or GenTopJets.
To test this in future, I've added more hists to plot constituents.size() vs jet pt, eta, and index.
Also reshuffled & expanded comments about `do*JetConstituent*` options to make it clearer.
[only compile] since the current config doesn't store constituents at the moment so plotting wouldn't be useful

[102X] Fix bug when deciding to store jet PFcands; add test plots

---

core/include/Event.h
core/include/EventHelper.h
core/include/L1EGamma.h
core/include/L1Jet.h
core/include/NtupleObjects.h
core/include/SUHH2core_LinkDef.h
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriter.h
core/python/ntuple_generator.py
core/src/AnalysisModuleRunner.cxx
core/src/EventHelper.cxx
core/src/classes.h
core/src/classes_def.xml

Store L1 triggers prescales, because if your trigger prescaled it's most probably done at L1. 
Also copied "doL1seed"  code from 94X_v3, which might be useful for L1 prefiring studies with 2017 data. Enabled for testing, should switched off by default in the production.

[102X] add stuff for advanced trigger studies

---

core/plugins/NtupleWriter.cc
core/plugins/NtupleWriter.h
core/plugins/NtupleWriterJets.cxx
core/plugins/NtupleWriterJets.h
core/python/ntuple_generator.py
examples/config/ExampleJetConstituents.xml
examples/src/ExampleModuleJetConstituents.cxx

Taking inspiration from how TopJets are handled, introduce `NtupleWriterGenTopJet` class to be able to handle complex setup for GenTopJets.
It's complex because we may want grooming applied, storing subjets, but also calculating substructure & other quantities on the groomed jet (this requires 2 separate jet collections).
Crucially, the njettiness & ECF were not being calculated correctly previously, since they were being calculated on jets that only had subjets as their constituents. This is now fixed.
Now it is all tied together a bit more nicely, and provides more route for expansion if there are other variables to store.
We therefore have the following GenTopJet collections:
- ak8GenJetsFat: ungroomed, has tau_i, no ECF, no subjets
- ak8GenJetsSoftDropforsub: groomed, has tau_i, ECF, …

[102X] Use NtupleWriter class for GenTopJets, do substructure+grooming properly

---

common/include/ElectronIds.h
examples/src/ExampleModuleEGammaID.cxx

Like for `MuonIDs`, add in a callable class so it can be used wherever one would use an `ElectronId`. also updated egamma example to show usage, although not enabled currently as it affects testing IDs are being stored
Should make using tags more trivial.
[only compile]

[102X] generic callable electron IDs

---

core/python/ntuple_generator.py

To keep more in line with the TopJet collections, renames:
- `ak8GenJetsFat` -> `genjetsAk8Substructure`
- `ak8GenJetsSoftDropforsub` -> `genjetsAk8SubstructureSoftDrop`
(Annoyingly it is not allowed to put an underscore in a module name.)
These should be more helpful. Will also make a table, like for the Jets/TopJets.
No changes to values.

[102X] rename gen top jet collections

---

common/include/JetHists.h
common/include/JetIds.h
common/include/MCWeight.h
common/src/JetIds.cxx
core/include/AnalysisModule.h
core/include/Jet.h
core/python/ntuple_generator.py
scripts/compare_hists.C

add working points for b-taggers for 2016, 2017 and 2018;
change list of discriminators to enable storage of DeepCSV for AK4PUPPI in 2016v2
rename `Jet::btag_DeepFlavour()` to `Jet::btag_DeepJet()`
Check with Z'->ttbar selection for tight WP of each b-tagger on AK4PUPPI for samples of different years:

[102X] add b-taggers WPs for AK4 jets, rename Jet::btag_DeepFlavour() to Jet::btag_DeepJet(), specify era of process 

---

core/python/ntuple_generator.py
core/python/ntuplewriter_data_2017v2.py
core/python/ntuplewriter_mc_2017v1.py
core/python/ntuplewriter_mc_2017v2.py

Since we need separate GTs & Eras for 2017v1 and v2, this adds extra parameters `2017v1` &`2017v2` for `generate_process()`, and retires `2017` argument.
Also add in corresponding configs. Purposely excluded data 2017v1 config since it is not really useful as people will be using the 31Mar18 dataset, which is counts as 2017v2 for us.
Updated bits in `generate_process()` that are conditional on year arg, e.g. MET EE fix.
So now:
- RunIIFall17MiniAODv2 MC and 31Mar2018 data should use `2017v2` configs
- RunIIFall17MiniAOD MC should use `2017v1` config

[102X] Split 2017 config settings into 2017v1 & 2017v2

---

common/src/JetIds.cxx

Better handling of multiple 2017 years. Also make DeepCSVBTag and DeepJetBTag emit a message when the year is invalid, and return false explicitly.
[only compile]

[102X] Handle extra 2017 year for JetIDs

---

scripts/findAllNtupleDirs.py

Add in script to produce txt files of all Ntuple ROOT files & directories in all the XML files in all the "interesting" branches
Technically: does this by checking out fresh copy of UHH2 repo, and inside checks out each branch, then crawls through all XML files in `common/datasets`.
[ci skip]

[102X] Add script to iterate over XMLs and find ntuples

---

common/src/JetCorrectionSets.cxx

Explicit string concat very slow and memory hog. This is a trick that two or more consecutive string constants are considered equivalent to a single string constant when encountered (stolen from https://en.wikibooks.org/wiki/C_Programming/Preprocessor_directives_and_macros##define).
Also see detailed analysis in https://github.com/UHH2/UHH2/pull/1180#issuecomment-470183373
Summary: 13 GB RAM -> 1.3 GB RAM. 8.5 min -> 2.5 min.
[only compile]

[102X] Fix JEC preprocessor macros to avoid memory hog, slowdown

---

core/python/ntuple_generator.py

update pfDeepFlavourJetTags for all years as before and the rest only for 2016v2. For other years it should be copied from miniAOD. This should "fix" issue with changed DeepCSV for 2017 discussed in https://github.com/UHH2/UHH2/pull/1163
Note for the future: BTV POG does not proved support for b-taggers in PUPPI jets yet, therefore we store discriminators calculated in miniAOD for PUPPI jets if it's possible (i.e 2017 and 2018) and add it only for 2016v2, where it isn't calculated yet. However one should be careful with using it in 2016, since it isn't clear if the DNN training is applicable to 2016v2 data.

[102X] copy most of slimmed b-taggers from miniAOD

---

core/python/ntuple_generator.py

DiPFJetAve450 doesn't exist. The HF ones we only on for special runs and were heavily prescaled, not useful.

[102X] Remove unused or nonexistent trigger objects

---

core/include/Utils.h
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriterJets.cxx
core/plugins/NtupleWriterJets.h
core/src/Utils.cxx

Store PUPPI weights for jet constituents. Also tidied up the duplicate methods used for (gen)jet constituent storage, now only one copy in NtupleWriterJets.cxx.
Also improved on constituent check - previous checked deltaR and deltapT == 0f, which often fails for floats. Now checks relative difference is < 1E-6 OR absolute difference is < 1E-6, whichever is larger. The latter absolute diff is necessary for deltaR == 0 comparison, since both the absolute and relative differences are ~1E-7 or so, but the relative diff condition must be < 1E-13, which is never satisfied.
This should hopefully shave off some duplicates when storing constituents.

[102X] Puppi weights + tidying for jet constituents

---

core/plugins/NtupleWriterJets.cxx
core/plugins/NtupleWriterJets.h

Better way to get the PUPPI multiplicities from userFloats.
Also now does it for the subjets of puppi topjets.
To save time looping through all userFloat names unnecessarily, we now also do this only for jet collections with "puppi" in their name (case independent). This removes the need for the PUPPI specific producer to have the same name as the jet collection (my previous horrible hack that caused much woe, I don't know why I didn't think of this earlier).

[102X] Get PUPPI userFloats by matching strings to ignore producer's name

---

core/plugins/GenHOTVRProducer.cc
core/plugins/GenXConeProducer.cc
core/plugins/HOTVRProducer.cc
core/plugins/XConeProducer.cc

Dunno why they were in there, not necessary. Also had to add in std namespace because the HOTVR.hh had it in (see https://github.com/UHH2/HOTVRContrib/pull/2)
[only compile]

[102X] cleanup HOTVR headers from XCone producers

---

core/plugins/NtupleWriter.cc

Move pfparticle storage to before we run through all the jet modules.
Before, if you enabled `doAllPFParticles` and you also stored jet constituents, it would store all the pfparticles again after the jets' constituents as no duplicate checking. This way we fill it up first, then do the duplicate checking in `add_pfpart()`.
Unfortunately we don't test with `doAllPFParticles = True`, so the change won't be visible. Maybe need to add a test in with it enabled?

[102X] Move pfparticle storage earlier to avoid double filling

---

core/plugins/RekeyJets.cc
core/python/ntuple_generator.py
examples/config/ExampleJetConstituents.xml
examples/src/ExampleModuleJetConstituents.cxx

This "rekeys" the constituents of PUPPI jets to replace them with their equivalent from the packedPFCandidates (this is what is done for slimmedJetsPuppi in MiniAOD). This way, when we come to store the jet constituents, we do not end up storing "duplicate" PUPPI & PF particles that differ only in whether they have the PUPPI weight applied. Since we now also store PUPPI weight (#1190) the user can still do things with the jet constituents, so long as they remember to use the PUPPI weight.
Have done for jetsAk8Puppi, jetsAk8PuppiSubstructure_SoftDropPuppi, xconePuppi, hotvrPuppi, and all the xconeDijetPuppi collections. 
- Pros: now uniform behaviour across all PUPPI jet collections, save space by not duplicating particles.
- Cons: now people have to choose to apply PUPPI weight or not. …

[102X] Rekey PUPPI jet constituents

---

core/plugins/HOTVRProducer.cc
core/plugins/RekeyJets.cc
core/plugins/XConeProducer.cc
core/python/ntuple_generator.py

Instead of using RekeyJets producer + messy hacks, move rekeying for HOTVR & XCone into their respective producers. The now actually rekeys their subjets as well, which was missing from #1199 .
Rekeying subjets is easiest for these collections done in their producers, due to the fact that a pat::Jet does not allow you to remove subjets once added, so you end up with a messy set of subjets.
With this, all PUPPI jet collections (& their subjets) should be correctly rekeyed against packedPFCandidates.

[102X] Add rekey options to HOTVR & XCone producers, use it on PUPPI jets

---

core/python/ntuple_generator.py

So I _think_ compactifying all our gen particle pruning into 1 module instead of 2 may save us some memory. The content should be identical. I don't think it saves any processing time unfortunately.
All tests were done with TTHadronic 2018 MC with the "allConstits" config. I did it twice for the default config, and twice for this PR.  The two "default" runs are on different machines at different times, the compact pruning lines were done one after the other.
RSS does show some differences: here is the RSS **relative** to the 1st recorded event:
Note that it doesn't even agree in repeated running (e.g. blue & orange, red&green)...a very tricky metric 😕 
Looking at absolute RSS:
Not quite sure what to take away from the absolute values - running the same default config, the RSS drop by …

[102X] Simplify genparticle pruning into 1 module to possibly save some RSS memory

---

core/plugins/GenXConeProducer.cc

This solves a long-standing memory (RSS) leak that plagued MC samples. Short (2K evt) tests look promising, will run much long ones as well to check.

[102X] Use unique_ptr to avoid raw ptr leaking in GenXConeProducer

---

scripts/crab/crab_template.py

[ci skip]
e.g. now stores in `/store/user/xxxx/RunII_102X_v1/2018/` for `ntuplewriter_mc_2018.py`. Should handle `2017v2` as well OK.

[102X] Add CRAB output subdirectory using year from pset filename

---

common/include/CommonModules.h
common/include/Utils.h
common/src/CommonModules.cxx
common/src/JetCorrections.cxx
common/src/Utils.cxx

MET filters now year-dependent, since some are run during the ntupleisation. To aid this (plus later things) have added in a `Year` enum class with helper function `extract_year(uhh2::Context)`. 
(I left in the commented-out filters so it's obvious that they've been considered but turned off for now, rather than forgotten about)
Also fix for `JetResolutionSmearer` since it was using a non-existent default file. It now checks first if file exists. It also now chooses a default file based on the Year. (NB the JER SF are still not auto year-chosen, but the user can also specify them in the constructor, so not quite sure how to handle this right now.)
[only compile]

[102X] Add Year enum; update MET filters in CommonModules; fixes for JetResolutionSmearer

---

common/include/JetCorrections.h
common/src/JetCorrections.cxx
core/include/Utils.h
core/src/Utils.cxx

Following on from #1218, this changes `JetResolutionSmearer` so that it now has 2 constructors to handle all the year-dependence:
- one takes no arguments apart from usual `uhh2::Context`, and tries to automatically figure out the correct resolution txt file and SFs for the given year & JetCollection name (AK4 vs 8, CHS vs PUPPI)
- one requires arguments to specify both the resolution txt file and the SFs (since both are year-dependent)
Note that this does break existing uses of the constructor that specified only the SFs; however they would actually be incorrect anyway (since potentially using wrong resolution txt file), so it's good that analysis code is aware of this change.
This means that the `JetResolutionSmearer` object in `CommonModules` is now fully-automated (as per the 1st …

[102X] Improve JetResolutionSmearer

---

core/plugins/NtupleWriter.cc
core/plugins/NtupleWriterJets.cxx

In single lepton datasets some events (<0.01%) contain jets with pt around 3e4. To avoid code crash, default jet pt for constituents storage increased to 2e6.

[102X] increase default pt for jet constituence storage

---

common/include/JetHists.h
common/src/JetHists.cxx

New definition of BTagEffiHists class with templats to use it with both CSV and DeepCSV working points. Users will now have to specify the btagging class they are using.
example:
```
std::unique_ptr<BTagMCEfficiencyHists<DeepCSVBTag>> hists_btag_eff;
hists_btag_eff.reset(new BTagMCEfficiencyHists<DeepCSVBTag>(ctx,"BTagLoose",DeepCSVBTag::WP_LOOSE));
```
[only compile]

[102X] New definition of BTagEffiHists class with templates

---

common/src/CommonModules.cxx
core/plugins/NtupleWriter.cc
core/plugins/NtupleWriter.h
core/python/ntuple_generator.py

- Adds `extra_trigger_bits` argument to NtupleWriter to allow storing of arbitrary bits (any module that produces a `bool`). These get stored like other trigger bits, but as `Extra_*` to avoid clashing with existing trigger names
- Use this to store BadPFMuonFilter now, which is now run as a tagger instead of filtering events
- Update `CommonModules` to use this new flag for 2016v2 samples

[102X] Add ability to store extra trigger bits; use for BadPFMuonFilter instead of in veto mode

---

scripts/crab/crab_template.py

Request name in `crab_template.py` now improved: can handle data run periods (previously would only return e.g. 'JetHT' for all run years & periods), long names (CRAB has maximum of 100 char), different versions, shorten a few more common generator strings, add MC campaign name. Also adds in time + date to aid with submissions over different days.
examples:
| Dataset | Request name |
| ---------- | ---------- |
| /JetHT/Run2018A-17Sep2018-v1/MINIAOD | JetHT_2018A_v1_1106_29_Apr_19 |
| /SingleElectron/Run2017B-31Mar2018-v1/MINIAOD | SingleElectron_2017B_v1_1106_29_Apr_19 |
| /JetHT/Run2016B-17Jul2018_ver1-v1/MINIAOD | JetHT_2016B_ver1_v1_1106_29_Apr_19 |
| /JetHT/Run2016B-17Jul2018_ver2-v1/MINIAOD | JetHT_2016B_ver2_v1_1106_29_Apr_19 |
| /JetHT/Run2016B-17Jul2018_ver2-v2/MINIAOD | …

[102X] Better CRAB request names
